import { ProductType, BlogPostType } from "@/types";

export const mockProducts: Omit<ProductType, "id" | "createdAt">[] = [
  // === RAW NEST ===
  {
    name: "Yến Sào Đảo Thiên Nhiên",
    slug: "yen-sao-dao-thien-nhien",
    description: "**THÔNG TIN SẢN PHẨM**\nYến sào nguyên tổ loại 1 được thu hoạch trực tiếp từ các hang động hoang dã tại vùng đảo yến Khánh Hòa. Sản phẩm trải qua quá trình tuyển chọn và kiểm định vệ sinh an toàn thực phẩm khắt khe, cam kết 100% nguyên chất, không độn phụ gia, không tẩy trắng hay dùng chất bảo quản. Tổ yến dệt sụn, kết cấu chắc chắn, giữ nguyên hàm lượng dinh dưỡng thiết yếu gồm Protein, Axit amin và các khoáng chất đa vi lượng.\n\n*Câu chuyện sản phẩm:*\nBên những vách đá dựng đứng của hòn đảo ngọc tít tắp khơi xa, nơi quanh năm đón gió biển mặn mòi và những con sóng tung bọt trắng xóa, loài chim yến hoàng gia đã dệt nên những tổ yến diệu kỳ. Yến Sào Đảo Thiên Nhiên là kết tinh của đại dương mênh mông, mang giá trị dinh dưỡng cao nhất, là món quà quý giá bồi bổ nguyên khí vượt thời gian.",
    shortDescription: "Tổ yến hoang dã khai thác từ đảo Khánh Hòa. Sợi yến sụn dày, nguyên chất 100%, không hóa chất mài mòn.",
    price: 2800000,
    originalPrice: 3200000,
    images: ["/images/products/raw-island-1.png"],
    category: "RAW",
    benefits: ["Bổ sung dinh dưỡng toàn diện, phục hồi sức khỏe nhanh", "Hỗ trợ tiêu hóa, làm sạch hệ hô hấp vòm phổi", "Chứa nhiều khoáng chất kẽm, canxi bồi bổ cơ bắp và xương khớp", "Giúp cải thiện làn da từ sâu bên trong cơ thể"],
    usage: "**HƯỚNG DẪN SỬ DỤNG CHUẨN KHOA HỌC:**\n1. Ngâm nở: Đặt tổ yến vào bát nước sạch, ngâm từ 3 đến 4 giờ cho đến khi các sợi yến tơi hoàn toàn.\n2. Rút lông: Dùng nhíp chuyên dụng nhặt sạch tạp chất và lông tơ mỏng. Tráng nhẹ qua rây lọc nước.\n3. Chưng cách thủy: Cho yến vào thố, chưng ở nhiệt độ dưới 85°C trong 30-35 phút. Thêm đường phèn tinh khiết vào 5 phút trước khi tắt bếp.\n\n*Nghệ thuật thưởng thức:*\nKhi chén yến còn nghi ngút khói ngai ngái hương vị của biển, hãy tĩnh tâm thưởng thức chậm rãi từng ngụm nước dẻo quánh thanh mát. Không gì tuyệt vời hơn lúc này là để năng lượng thuần khiết đánh thức các tế bào đang mỏi mệt trong cơ thể bạn.",
    tags: ["premium", "island", "natural", "gift"],
    stock: 50,
    averageRating: 4.8,
    reviewCount: 45,
    featured: true,
    active: true,
    weight: "100g",
    origin: "Khánh Hòa, Việt Nam",
  },
  {
    name: "Yến Sào Hang Cao Cấp",
    slug: "yen-sao-hang-cao-cap",
    description: "**THÔNG TIN SẢN PHẨM**\nDòng yến hoang dã siêu cấp độ được thai nghén từ nền đá thạch nhũ tự nhiên của những hang động u tối, tĩnh lặng hằng trăm năm tuổi tại Bình Thuận. Yến hang tự nhiên hấp thụ lượng lớn các hợp chất Sắt (Fe), Kẽm (Zn) và Mangan tự nhiên, làm tổ cứng cáp, mang sắc vàng cam nhẹ đặc trưng. Sở hữu độ hiếm có khó tìm, Yến hang tự hào với hàm lượng Sialic Acid vượt ngưỡng chuẩn so với yến nhà, trở thành lựa chọn lý tưởng cho người đang cần phục hồi thể trạng nặng.\n\n*Câu chuyện sản phẩm:*\nSâu thẳm trong những hang động rêu phong, nơi ánh sáng hiếm hoi chiếu xuyên qua kẽ đá hẹp, loài Yến cổ đại dệt nôi trên những thạch nhũ rỏ nước. Hàm lượng vi lượng đất khoáng rỉ rả ngày qua ngày đã nhuộm tổ yến bằng sắc độ vàng trầm tích. Đó chính là một liều linh dược cô đặc mà Mẹ tự nhiên đã ban tặng nhằm nuôi dưỡng sức mạnh hồi sinh, chỉ dành riêng cho những thể trạng yếu suy đang chờ được khôi phục mãnh liệt.",
    shortDescription: "Tổ yến hoang dã trăm năm từ hang thạch nhũ. Hàm lượng khoáng vô biên, siêu hồi phục, siêu phục hồi.",
    price: 4500000,
    originalPrice: 5000000,
    images: ["/images/products/raw-cave-1.png"],
    category: "RAW",
    benefits: ["Sở hữu chỉ số vi khoáng cực cường từ vách hang đá", "Hồi sức cấp tốc cho người suy nhược nặng", "Nâng cấp cực lớn rào chắn hệ hệ miễn dịch"],
    usage: "**HƯỚNG DẪN SỬ DỤNG CHUẨN KHOA HỌC:**\n1. Chuẩn bị: Vì tổ yến có sợi cứng do khoáng hóa tự nhiên, bạn cần ngâm bằng nước sạch trong khoảng 4 đến 5 giờ cho đến khi rời cấu trúc tảng lớn.\n2. Chưng yến: Hấp cách thủy nhiệt độ không cao quá 85°C trong khoảng tối đa 40 phút. Nêm chút tuyết nhĩ hay kỷ tử hữu cơ vào 10 phút chót để dược vị thô mộc quyện hòa tối đa nhất.\n*Lưu ý: Không lạm dụng dội nước sôi quá nóng để ủ.*\n\n*Nghệ thuật thưởng thức:*\nHương thơm dai nhách và mùi thơm thô mộc của Yến hang rất rõ rệt. Cách dùng đỉnh đạc nhất là bưng bát gốm sứ từ từ lách sợi vào cuống não sảng khoái đánh bật những sự trống rỗng trong tâm hồn rã nát mỏi mệt của não bộ.",
    tags: ["premium", "cave", "rare", "health"],
    stock: 20,
    averageRating: 4.9,
    reviewCount: 28,
    featured: true,
    active: true,
    weight: "100g",
    origin: "Bình Thuận, Việt Nam",
  },
  {
    name: "Yến Sào Lông Nguyên Chất",
    slug: "yen-sao-long-nguyen-chat",
    description: "**THÔNG TIN SẢN PHẨM**\nYến sào nguyên bản khai thác mộc, chưa qua bất cứ khâu can thiệp rửa dọn xử lý nước làm lông nào. Sản phẩm được thu hoạch trực tiếp tại các hệ thống nhà yến kiểm soát chuẩn, bảo toàn nguyên cấu trúc nguyên vẹn của dãi yến, lông vũ và một chút mảnh trứng vụn. Đảm bảo 100% không vương hóa chất mài mòn tẩy màu. Khách hàng trực tiếp quản lý độ tươi nguyên chất thông qua khâu nhặt lông tỉ mẩn.\n\n*Câu chuyện sản phẩm:*\nVẻ đẹp của sự thô ráp chân thật! Lựa chọn Yến lông là lựa chọn đối mặt trực diện với món quà nguyên sơ nhất, không chải chuốt bề mặt. Giống như tình thương tảo tần của thế hệ trước, việc kiên nhẫn cúi người lựa từng mảng tơ đen nhách để trả lại ánh sáng cho một mảng yến ngọc trắng muốt là thước phim đong đầy sự cảm mến tự thân.",
    shortDescription: "Tổ nguyên bản không vệ sinh cơ học, giữ 100% mùi nguyên thô của nhà yến thiên nhiên hoang dã.",
    price: 1800000,
    originalPrice: 2200000,
    images: ["/images/products/raw-feather-1.png"],
    category: "RAW",
    benefits: ["Bảo vệ trọn vẹn lớp bề mặt tế bào yến nhạy cảm với nước rửa công nghiệp", "Minh bạch 100% về độ thật của sản phẩm", "Tối ưu hóa giá thành do giảm chi phí dịch vụ làm sạch thủ công"],
    usage: "**HƯỚNG DẪN SỬ DỤNG CHUẨN KHOA HỌC:**\n1. Chuẩn bị công cụ: Nhíp gắp siêu nhọn, bát nước ấm nhỏ, ánh sáng tốt tập trung.\n2. Làm mềm: Ngâm phần yến lông trong thau nước sạch khoảng 2-3 tiếng để tổ rũ chân nở ra.\n3. Tẩy tạp: Tách sợi từ từ gắp hết những chấm đen vụn và mẩu lông rải rác. Vừa làm vừa nhúng qua bát nước trong để lông thôi bám. Thao tác tốn mất 30 phút mỗi tổ lớn cho người chưa thân quen.\n4. Chế biến: Có thể sử dụng ngay để bỏ tủ lạnh phần yến vừa rửa xả và chưng lên ăn theo định mức khuyên dùng 5g / 1 người /1 ngày.\n\n*Nghệ thuật thưởng thức:*\nThưởng thức yến lông vừa rửa tại nhà giúp lan tỏa vị tanh mộc mạc y hệt mùi sương biển khơi dạt dào ấp vào lòng. ",
    tags: ["natural", "affordable", "health"],
    stock: 80,
    averageRating: 4.5,
    reviewCount: 62,
    featured: false,
    active: true,
    weight: "100g",
    origin: "Nha Trang, Việt Nam",
  },
  {
    name: "Vụn Yến Sào Tự Nhiên",
    slug: "vun-yen-sao-tu-nhien",
    description: "**THÔNG TIN SẢN PHẨM**\nVụn yến quy tụ từ quá trình xử lý, cắt dọn biên độ thẩm mỹ và mài gọt tổ yến cao cấp. Vì xuất thân từ yến tổ loại 1 nên giá trị sinh hóa học dinh dưỡng Protein không hề thay đổi khác biệt. Các dải sợi nát, mỏng và dẹt hơn do vỡ vụn cơ học tự nhiên chứ không chịu lực cắt băm nhuyễn xảo trá. \n\n*Câu chuyện sản phẩm:*\nVụn Yến là những vóc ngọc nhỏ bị phân cách ra khỏi cấu trúc liền khối trang trọng, mang theo tấm lòng thiết thực khiêm nhường. Không cần ngoại hình đắt đỏ hoàng kim, vụn yến sinh ra để len lỏi âm thầm vào bát cháo ăn dặm mỗi sáng của con thơ hay trở thành nụ cười khỏe khoắn trên môi người mẹ lớn tuổi khi tính toán một ngân sách gia đình thông minh mà khéo léo.",
    shortDescription: "Giá trị bổ trợ từ mảnh vụn hữu ích, dinh dưỡng tinh hoa y chang dòng cực phẩm. Lựa chọn chi tiêu lý tưởng thông minh.",
    price: 900000,
    originalPrice: 1200000,
    images: ["/images/products/raw-broken-1.png"],
    category: "RAW",
    benefits: ["Tiết kiệm đáng kinh ngạc cho bữa tẩm bổ hằng ngày", "Dễ dàng ngấm và xay nhuyễn cực tốt cho trẻ biếng ăn cần nhai nuốt nhẹ", "Tránh việc xài phí nguyên mảng to vượt cỡ"],
    usage: "**HƯỚNG DẪN SỬ DỤNG CHUẨN KHOA HỌC:**\n1. Rã yến siêu nhanh: Vì có kết cấu cắt gãy mỏng tơi xốp, chỉ tốn 15-20 phút ngâm trong thố nước lọc là vụn đã no bụng nở xoè xốp đều.\n2. Cách thủy hay Hấp: Vì thời gian phá hủy cấu trúc của các mảnh vụn diễn ra mau lẹ, tuyệt đối không chưng nước vượt quá 20 phút. Nếu kết hợp cháo thịt bằm, hãy nấu chín thịt cháo trước múc ra ngoài xong trộn Yến lên nắp nóng ngậm dầm tan vô để chất xám khỏi bốc hơi cạn ráo.\n\n*Nghệ thuật thưởng thức:*\nVụn yến mềm mịn xốp xượt không dai như yến nguyên tảng to nhưng dễ mút tụt ực phát qua thực quản nuốt nhẹ tênh dỗ dành dạ dày tổn thương khốc liệt nhất của người bệnh lớn tuổi.",
    tags: ["affordable", "daily", "family"],
    stock: 150,
    averageRating: 4.3,
    reviewCount: 89,
    featured: false,
    active: true,
    weight: "100g",
    origin: "Nha Trang, Việt Nam",
  },

  // === REFINED ===
  {
    name: "Yến Sào Tinh Chế Trắng",
    slug: "yen-sao-tinh-che-trang",
    description: "**THÔNG TIN SẢN PHẨM**\nDòng yến quốc dân cao cấp được xử lý 100% bởi đội ngũ nghệ nhân chuyên nghiệp tại xưởng yến tiêu chuẩn ISO. Từ tổ yến khô thô ráp ban đầu, toàn bộ rác tạp và lông vũ li ti đều đã được lọc gắp cẩn thận không dùng tẩy trắng Javen, rồi dệt ép vút lên rập khuôn thuyền võng thanh lịch. Cấu trúc tổ vững không vỡ móp, ngà ngà ánh tuyết phô bày một diện mạo tặng phẩm sạch, tinh khiết 100% không tồn dư rác nước.\n\n*Câu chuyện sản phẩm:*\nĐược nhào nặn dưới đôi bàn tay điêu luyện của hơn 50 nghệ nhân lâu năm ròng rã hàng chục giờ - Yến Sào Tinh Chế Trắng mang trong mình vẻ đẹp xuất sắc của một nàng thơ tuyết bay bổng lướt mượt qua vòm kính. Nó là giải pháp cực kỳ tốc chiến tôn vinh vẻ thanh lịch của giới tinh hoa bận rộn.",
    shortDescription: "Sạch sẽ 100%, dệt khuôn thuyền nhã vặn, sẵn chế biến ngay không dây tạp khuẩn nào. Giải pháp Quà Biếu hạng A.",
    price: 3500000,
    originalPrice: 4000000,
    images: ["/images/products/refined-white-1.png"],
    category: "REFINED",
    benefits: ["Tiết kiệm vĩnh viễn quỹ thời gian chế biến gắp rửa dọn lông nan giả nhái", "Sợi dệt liên kết dài, tạo thị giác mãn nhãn cao quý cúng tế biếu người", "Giữ nguyên nồng độ Protein gốc nguyên hạt"],
    usage: "**HƯỚNG DẪN SỬ DỤNG CHUẨN KHOA HỌC:**\n1. Chuẩn bị tức thì: Do tổ yến đã lọc tiệt trùng hút ẩm khô đét, bạn chỉ cần một cái thố nhúng yến vào nước khoảng 30 chục phút đổ lại rã mềm dẻo xoắn xuýt.\n2. Chưng hầm: Đặt thố lên bộ phận nhiệt nhỏ chưng âm ỉ tầm 25 - 30 phút là vừa phải độ xéo. Nhỏ đường phèn và có thể rưới thêm 2 rễ gừng lát hâm nóng dạ phế.\n\n*Nghệ thuật thưởng thức:*\nSợi dệt của Yến Trắng có độ quyện dai nẩy bật. Gợi ý bạn hãy thực hành một nồi Chè 'Lục Phẩm Tiến Vua' với Bạch quả, Hạt Chia vàng, Tuyết Nhĩ ngâm mộc, Táo đỏ khô... Cảm nhận 1 buổi ăn tráng miệng xa xỉ thanh cao mượt mà tột độ ở nơi vòm miểng.",
    tags: ["premium", "clean", "gift", "convenience"],
    stock: 60,
    averageRating: 4.7,
    reviewCount: 56,
    featured: true,
    active: true,
    weight: "100g",
    origin: "Ninh Thuận, Việt Nam",
  },
  {
    name: "Sợi Yến Vàng Cao Cấp",
    slug: "soi-yen-vang-cao-cap",
    description: "**THÔNG TIN SẢN PHẨM**\nCực phẩm quý hiếm được truy xuất từ loài chim yến trưởng thành hơn 10 tuổi mang hệ gen chịu biến sắc mạnh mẽ theo mùa, đắp lên kết cấu Sợi Yến vàng óng rạng ngời thiên nhiên. Những phân tử khoáng chất dày đặc xen lẫn tạo cho móng tổ to hơn, dai sần sật mập dầy thịt. Nó có tỷ lệ tồn tại dưới 5% mỗi vụ thu kho hoạch, là một bảo ngọc cất giấu giá trị bồi phục rất lớn về hệ thống luân hồi chuyển máu tạo oxy do tích luỹ lượng Sắt khoáng Fe++ cao chót vót.\n\n*Câu chuyện sản phẩm:*\nNếu Yến Trắng là Nàng thơ tuyết mơ màng thì Sợi Yến Vàng chính là Nữ hoàng mặt trời cháy nắng vinh quang rực rỡ. Rất hiếm hoi tự nhiên chịu nhả ngọn hoàng kim vào chiếc vòm hốc ẩm, biến chất lỏng trắng tinh khiết thành hòn quặng dẻo kẹo dai nhách ánh nhũ vô nhị cực sành cực kén. Nhâm nhi nó là xác nhận vị thế am tường đắt kỷ khó nhằn của dân tinh anh chuyên sành ẩm thực.",
    shortDescription: "Quặng Hoàng Kim siêu dai giòn hiếm có, hấp thụ oxit kẽm khoáng dồi dào, hàm lượng bổ rực sức chiến binh sống dai.",
    price: 5200000,
    originalPrice: 5800000,
    images: ["/images/products/refined-golden-1.png"],
    category: "REFINED",
    benefits: ["Nâng lượng rực rỡ sản sinh mô tạo máu đỏ oxy cao nhất", "Thương vị nồng đặc đậm khó xoáy nhầm qua dòng thô mộc xơ nhạt", "Duy trì thanh xuân da thịt săn dẻo chắc"],
    usage: "**HƯỚNG DẪN SỬ DỤNG CHUẨN KHOA HỌC:**\n1. Chuẩn bị: Sợi cộm vàng ngấm nước lì lợm hơn, cần ngâm dãn đến lúc nở mọng đùn khoảng tầm 45 phút hơn.\n2. Bí Quyết Lửa: Để khắc chế cái cơ sần sật của nữ hoàng dại, phải áp dụng đòn răn lửa 2 nấc cao cách thủy 15 phút đầu sôi nhẹ cho xụp nở dãn sụn nấm gai, rồi sau 15p nhão ra mới bỏ đường hạ sốc ninh thắt kết dính bùng vị.\n\n*Nghệ thuật thưởng thức:*\nMùi tanh biển rất trầm dày cuốn quýt dai xộc. Yến râm nảy độ giòn tanh tách khi cắn chạm vỡ trên hàm nha làm xiêu lòng bao tay sành chấn động. Dùng với ít hạt sen non tươi ninh luộc chín trước để bổ âm toàn diện tủy mạch.",
    tags: ["rare", "premium", "golden", "mineral"],
    stock: 15,
    averageRating: 4.9,
    reviewCount: 19,
    featured: true,
    active: true,
    weight: "50g",
    origin: "Khánh Hòa, Việt Nam",
  },
  {
    name: "Yến Nhỏ Cho Bé",
    slug: "yen-nho-cho-be",
    description: "**THÔNG TIN SẢN PHẨM**\nDạng bào chế đặc thù được cấu thành từ phần yến bụng sườn cực tơ mượt cắt ngắn. Yến ép dập cẩn thận thành khuôn khối lượng đồng xu vóc nhỏ nhác tròn dẹt đạt 1.5 - 2.5 gram chuẩn. Với quá trình cắt khúc tinh sạch và kết xốp siêu hút nước, Yến chuyên dụng cho bé loại bỏ nguy cơ sặc rối mắc dạ con họng non, hỗ trợ hệ tiêu hoá trẻ sơ sinh 1-4 tuổi đào thải trơn chảy nhẹ gánh êm đẹp mà nạp 100% mộc miên sức kháng độc hại.\n\n*Câu chuyện sản phẩm:*\nYến Nhỏ Cho Bé mang trọn trái tim của tình mẫu tử và sự thấu cảm rưng rưng. Một viên yến nhíu nhéo trắng tuyết vo tròn cúc áo tưởng chừng mong manh nhưng khi thả vào cháo húp nở toè xòe mây trắng tinh là cứu tinh đánh đuổi cơn khóc bực biếng ăn còi cọt còi nhẵng xương tay bần thuồng luồng. Nó là lời hứa vô thanh mạnh mẽ nụ cười bảo chứng cân nặng mũm mĩm tương lai.",
    shortDescription: "Đồng xu yến nhỏ mềm tơ cắt khúc siêu cấp phù hợp niêm mạc trẻ trâu ấu, tăng cao hàm kháng sinh tự nhiên siêu khuẩn.",
    price: 2000000,
    originalPrice: 2400000,
    images: ["/images/products/refined-baby-1.png"],
    category: "REFINED",
    benefits: ["Tan vỡ mịn mượt, đẩy mạnh chuyển hóa không ngâm đầy hơi chướng căng bụng", "Chuẩn khẩu phần 1 lần ăn không cần trĩu cân tiểu li rạch rách bao", "Nuôi nền đề kháng xưng phổi tị mũi siêu cường đại"],
    usage: "**HƯỚNG DẪN SỬ DỤNG CHUẨN KHOA HỌC:**\n1. Chuẩn bị định lượng: Một em bé ranh biếng từ 1-3 tuổi chỉ dùng nửa vóc tới 1 xu (1.5g) cách ngày bổ một cữ tút rưỡi. Ngâm nởi bung khoảng 15 phút tơi vụn lá liễu.\n2. Chế độ pha chế: Khuyến cáo không bõ đường phèn quá nhiều nếu nhóc ho lợmm. Tốt nhất đem hấp lồng nhão cách 15 phút thôi.\n\n*Nghệ thuật thưởng thức:*\nKẻ sành nhất hãy khuấy xay nhẹ ngô non vàng luộc chín thành súp kem cốt pha vào yến nhuyễn trong lúc bé chóp chép. Hương ngô vàng chanh ngật ngào xua tanh tưởi bọt khiến trẻ mê li hút tụt hạt cặn chóp tận hớp muỗng cuối.",
    tags: ["baby", "safe", "immunity", "brain"],
    stock: 70,
    averageRating: 4.6,
    reviewCount: 73,
    featured: false,
    active: true,
    weight: "50g",
    origin: "Việt Nam",
  },
  {
    name: "Hộp Quà Yến Sào Premium",
    slug: "hop-qua-yen-sao-premium",
    description: "**THÔNG TIN SẢN PHẨM**\nBộ sản phẩm tổng hợp xa xỉ đáp ứng tiêu chí sang trọng lễ nghi VIP cực độ. Hộp Quà Premium bao vây toàn diện chu trình biếu tặng với vỏ cứng sơn mài ánh lụa bóng dập chìm vân gấm lộng lẫy, cốt lót xốp nệm chống va quăng sốc rung xẹp xệ. Bộ khí tài bên trong khoe sần sừng 1 xấp Yến hoa trắng thanh nhã chuẩn nguyên cườm gáy 100gr dệt mĩ miều, áp đảo uyên ương với 2 hũ Yến Chưng thủ công 70ml nắp vặn ánh kim cương sẵn tiện tốc uống nhấp môi. Món quà bệ vệ khí uy ngút ngàn vượt xa khuôn khổ tầm thường.\n\n*Câu chuyện sản phẩm:*\nViệc trao món Yến Sào đại diện cho lời nguyền sinh mệnh chúc 'Phúc Thọ An Khang'. Hộp quà nới ra trước mắt như một mật điện uy mãnh triều nguyên hoàng đế cung phụng mẫu nghi. Sự phối hợp vừa được chứng thực qua món nhấp tươi sảng khoái liền mạch vừa ngâm vóc yến chưng dài tự tại khẳng định trọn thành ý sâu nẳm không vụ lợi mà tràn chàn ân sủng nết hiếu thảo.",
    shortDescription: "Combo Lễ Nghi Uy Mãnh VIP Thượng Đỉnh chốt hạ dâng tặng ngoại giao - 100g Yến trắng ép cườm & 2 Hũ ngọc rót rực.",
    price: 4800000,
    originalPrice: 5500000,
    images: ["/images/products/refined-giftbox-1.png"],
    category: "REFINED",
    benefits: ["Nâng tầm giá trị ngoại giao biểu dương phô bày bộ sưu tập cực phẩm", "Cam kết set quà vẹn toàn đủ táo đỏ/đường cung cấp", "Thiết thực tiện nghi hai đường lối: Dùng ngay hoặc Tự nấu vui thảnh thơi"],
    usage: "**HƯỚNG DẪN SỬ DỤNG CHUẨN KHOA HỌC:**\n1. Sản phẩm Hũ Chưng Pha Sẵn: Vặn niêm phong và hút ngay trọn 1 hầm dồn vitamin ập vào lúc bụng dạ hống đói vặt chiều. Để lạnh thêm băng the râm ran sung sướng.\n2. Sản phẩm Tổ Trắng 100gr: Bảo quản khô ngăn thoáng mát hầm rượu hoặc kệ cao không mốc tối. \n\n*Nghệ thuật thưởng thức:*\nSử dụng phụ kiện thiệp mạ kim đính ở mép góc xô lụa viết nắn viền chữ tri ân gửi phụ mẫu bề trên để khai thông hoàn bị sự sung tức nghi thức báo hiếu kính túc bành tổ thiên hạ nhân phẩm mười mươi thiện tâm vô mạn.",
    tags: ["gift", "premium", "combo", "holiday"],
    stock: 30,
    averageRating: 4.8,
    reviewCount: 34,
    featured: true,
    active: true,
    weight: "Combo 100g khô + 2 hũ chưng",
    origin: "Việt Nam",
  },

  // === READY TO EAT ===
  {
    name: "Yến Chưng Nhân Sâm",
    slug: "yen-chung-nhan-sam",
    description: "**THÔNG TIN SẢN PHẨM**\nPhiên bản đóng hũ nhỏ nhắn gọn bưng được chế luyện công xưởng khép kín hoàn toàn vô trùng. Yến Sào sợi dệt mật độ cao hòa quyện cùng dung dịch đường phèn chắt lọc từ cao rễ Nhân Sâm Hàn Quốc trứ danh (bắt buộc trồng từ trên 5 năm tuổi rễ già gân) xé lát, thanh trùng siêu tốc nhiệt cao Paster 121 độ tiêu diệt 100% bóng nha bào ôi mốc. Không bổ sung chát bảo quản hóa học axit xít, nước cốt đặc rền sệt dẹo vắt đọng sức năng thần kỳ của vương dược bảo vệ huyết quản cường lộc dương.\n\n*Câu chuyện sản phẩm:*\nKhi mà nhịp sống khốc liệt của đô hội đẩy bật thân xác xuống mỏi mệt cực điểm uề uải chán nản váng đầu, vị thuốc đại thần Nhân Sâm hòa lướt dẻo quánh cùng Yến tinh chất hất tông lên hương rượu nồng ấm ức chát rát hăng tạc dạ. Nó vọt xoáy sự nứt gãy cơ trướng và đẩy xông dòng lửa bừng phực ấm lòng nội tạng hồi xuân dậm dực khí dương bất khuất đánh sập muộn phiền.",
    shortDescription: "Giam giữ Sức Ấm Đại Dương & Linh Khí Rễ Hồng Sâm 5 Tuổi bừng bừng sức mạnh sống bứt phá khỏi tụt ức váng mệt.",
    price: 180000,
    originalPrice: 220000,
    images: ["/images/products/readytoeat-ginseng-1.png"],
    category: "READY_TO_EAT",
    benefits: ["Hồi đáp sinh dực, phực nhãn sức đờ đoái lao tâm", "Phục cường làm trơn tru cọ xoáy xua đuổi phong hàn tà lạnh ướt người", "Tiện ích thần sầu húp một giây xong chuyện bổ 3 ngày dai"],
    usage: "**HƯỚNG DẪN SỬ DỤNG CHUẨN KHOA HỌC:**\nLắc xoay tay nhẹ nhàng vẩy đánh đều lát sâm cặn li ti hòa lẫn sụn yến lấp võng để không cô đọng. Vặn bật núm 'bốp' chân không và uống ực một chặp cạn li kì vòi vọt. TUYỆT ĐỐI HỮU DỤNG lúc 9H SÁNG. Không dùng trước khi bước lên giường ban đêm bởi nhiệt huyết phực cực đoan làm căng não khó nhắm thức trằn qua ngày muộn gắt cỏng.\n\n*Nghệ thuật thưởng thức:*\nCó thể thả ngâm cả lọ vô bát nước nóng ấm sùng sục 10 phút sau đó mới mở cho dòng lưu nóng sâm kích bốc vị hương khốc liệt nghẹt mũi tỏa mùi nam nhi chí nam vương đại hùng tráng nhẩm vào cổ họng nuốt cái ót mĩ thăng hoa.",
    tags: ["convenient", "ginseng", "health", "daily"],
    stock: 200,
    averageRating: 4.6,
    reviewCount: 124,
    featured: true,
    active: true,
    weight: "70ml x 1 hũ",
    origin: "Việt - Hàn Hợp Tác",
  },
  {
    name: "Yến Chưng Đường Phèn",
    slug: "yen-chung-duong-phen",
    description: "**THÔNG TIN SẢN PHẨM**\nDòng Base kinh điển chưng hầm kỹ thuật số vô trùng siêu chuẩn. Hàm lượng 10% Yến dệt mật đặc tươi phối chế thuần khiết tinh khiết tuyệt biên cùng đường phèn kết tinh 18 độ cữ giòn đanh thanh nản. Hũ thuỷ tinh trong veo đục khé không bóng cặn tạp phớt vẩn, kết dính bởi công nghệ áp tiêu khép nhiệt Paster hiện đại khắt khe chống bung lên men vỡ độc sinh khuẩn yếm khí.\n\n*Câu chuyện sản phẩm:*\nTrong một thế giới đầy những gia vị pha tạp chế lấp mặn chua, Yến chưng đường phèn đứng vững chãi vĩnh cửu như một bức tượng đài Tối Giản Mộc Miên thuần bạch dạt dào êm ả mộng. Ẩn mình sau lớp vỏ hũ nắp vàng khiêm tốn là vị ngòn ngọt lợt lẻo thanh bồng bềnh uốn xoa xịu vòm lăm rát xơ ho, ôm rúc và rửa trôi mọi căn cặn bã ô trọc nanh cọ.",
    shortDescription: "Chén mộc nước thanh phèn trôi vèo thanh tân y tế chơn láng mọi vết rát ho vòm xưng cúng kiến nội tạng trẻ lại.",
    price: 150000,
    originalPrice: 180000,
    images: ["/images/products/readytoeat-sugar-1.png"],
    category: "READY_TO_EAT",
    benefits: ["Tiêu giảm nội hỏa cháy bừng phổi viêm sặc họng đớn", "Hóa thạch cơn khát kiệt trạc hạ nhiệt cơ trơn láng bóng mĩ dạ mỏng bọc", "Tiện ghim xài húp lót trẻ non mẹ gầy bụng lả u"],
    usage: "**HƯỚNG DẪN SỬ DỤNG CHUẨN KHOA HỌC:**\nMở hộp dùng tức thì, cắm quất luôn hoặc xắp cất trong ngăn làm mát của khay quầy tủ lạnh nhiệt dưới 10 độ C uống sảng rân. Khẩu lệnh tốt nhất là vào 9h-10h tối lấn bấn để ru dạ ẩm thực nôi xoa bóp trút cạn mệt chìm nhung vào ngủ sâu lịm chết mệt mỏi ban cạn thấu.\n\n*Nghệ thuật thưởng thức:*\nHãy dùng chiếc muống gốm sứ múc gảy miết lốc từng bụp Yến quánh đường thanh lên vòm niêm mạc lưỡi, nhắm mắt xuôi văng để cặn sụn trượt êm mềm không dại gì dốc lọt luốt òng ọc kẻo vụt nhoát qua phí hoài.",
    tags: ["classic", "convenient", "family", "daily"],
    stock: 300,
    averageRating: 4.5,
    reviewCount: 156,
    featured: false,
    active: true,
    weight: "70ml x 1 hũ",
    origin: "Ninh Thuận",
  },
  {
    name: "Yến Chưng Nước Dừa",
    slug: "yen-chung-nuoc-dua",
    description: "**THÔNG TIN SẢN PHẨM**\nSáng kiến y dược học đan quyện Yến Sào băm nhuyễn cùng nguồn điện giải cấp nước thiên nhiên đệ nhất: Nước cốt quả Xiêm Dừa lùn Bến Tre mộc mạc. Sự chuyển hóa vi khoáng Magie, Canxi của nước dừa len lỏi thẩm thấu màng protein của yến đảo, kích bốc cấu hình Collagen non tăng cao và cho ra vị béo béo chua dịu nức nở thanh mây nồng. Đóng hũ diệt trùng hoàn toàn, chất dừa được cô màng mỏng bao bọc giữ 100% vị tươi trắng tinh đục dịu dẻo dai bùi xốp.\n\n*Câu chuyện sản phẩm:*\nMột sự khiêu vũ táo bạo dầm rợn của hai vua giải khát nhiệt đới vẫy vùng dưới nắng nóng. Nước dừa bẽo béo quánh vương lượn nấp cùng dãi yến thênh thanh chợp xoa dịu đi cơn khốc kiệt thiêu đốt bốc sương nám sạm đen của làn da phụ nữ dập thù lụa sương. Nó không chỉ là ly nước hám ngọt mà là thần dược giải áp nhan sắc mĩ từ rờ rỡ trong ánh mắt say đắm.",
    shortDescription: "Suối Lọc Giải Khát Đỉnh Cao Mùa Tóc Khô Nắng Nam - Khơi cấp nguồn nước làm mờ chân tàn nhang sắc bén bốc lột sạm tồi.",
    price: 170000,
    originalPrice: 200000,
    images: ["/images/products/readytoeat-coconut-1.png"],
    category: "READY_TO_EAT",
    benefits: ["Bồi lấp nước điện giải bù mồ hôi thoái trào mất canxi", "Phục hưng biểu bì bóc khô nẻ bong tróc tóc xơ vụn lả tả", "Vị ngon ngọt lạ lùng khó cưỡng thèm ừng ực nức thóp nhấp nhấp"],
    usage: "**HƯỚNG DẪN SỬ DỤNG CHUẨN KHOA HỌC:**\nKhoái khẩu uống rát lạnh cứng. Hãy dồn hũ dừa yến bỏ tủ đông 15 phút sương dộp giá rã đông nhẽ nhẹ rồi bật tung xé núm mút sù sụt ngay tận bờ não buốt đóng dẻo. Ngày nã 1 cữ bất thình lình mỗi xế trưa hạn hạ ngập mỏ quạt.\n\n*Nghệ thuật thưởng thức:*\nĐổ cốc yến đê mê ra pha lê vò vo cuống lá Bạc Hà ngái miên xen lẫn cùng rắc đá viên lốm chốm lốc rốc như ly Cocktail Thanh Xuân Chống Nám khóc thét trả lại 18 tuồi bừng nhan gắp.",
    tags: ["beauty", "coconut", "collagen", "women"],
    stock: 180,
    averageRating: 4.7,
    reviewCount: 98,
    featured: false,
    active: true,
    weight: "70ml x 1 hũ",
    origin: "Bến Tre x Khánh Hòa",
  },
  {
    name: "Yến Chưng Collagen Hồng Sâm",
    slug: "yen-chung-collagen-hong-sam",
    description: "**THÔNG TIN SẢN PHẨM**\nCực Phẩm Tam Vị Hội Tụ đột phá với nồng độ đậm đặc công nghệ y sinh hiện đại. Yến sào 15% tích hợp cùng dòng Collagen Peptide vi phân (kích thước siêu cực mỏng ngắm ruột xuyên mạch 300 Dalton) và rễ Hồng Sâm cường đạo sắc tía Hàn Quốc cọ bóp. Kết cấu hỗn hợp nhẫn đặc sẫm đục màu mận huyết, chống lại chuỗi phản ứng đứt gãy DNA phá nhão chảy xệ mụn nám từ 30 tuổi dập tới đâm xuồng phũ phàng.\n\n*Câu chuyện sản phẩm:*\nUy Quyền Vực Dậy Mảng Cắt Lão Hóa! Hũ yến quyền lực này gầm thét vị nhẫn đắng ban đầu trên đầu lưỡi, nhưng ngay lập tức bùng nổ vỡ tung sự ngọt ngào cuống quýt từ dạ phế xốc ngược bốc lên thanh khí rát mũi nồng ấm đê mê. Nó là cỗ máy quay ngược kim đồng hồ, buộc làn da chầu chực nhăn rút phẳng mịn lại trong ánh mắt ghen tị của phàm trần tuổi già rũ rượi xông tới đoạt hồn nhan nhụy đóa.",
    shortDescription: "Ma thuật đỏ thắm Cỗ Máy Thổi Ngược Lão Già Đứt Chuỗi DNA Chẩy Xệ bằng chốt nọc Hồng Sâm đan giăng sợi Yến Collagen thần dược.",
    price: 250000,
    originalPrice: 300000,
    images: ["/images/products/readytoeat-collagen-1.png"],
    category: "READY_TO_EAT",
    benefits: ["Xóa xụp lấp đầy võng rãnh cười vết cung đường nhăn vạt vạc bọng mắt giật", "Truyền nổ sinh lực nữ cường hooc môn buồng trứng ục âm thầm đẻ sức khoe vạm đỏ da thắm", "Hồi phục bấu gân chóp dính kết giằng sụn cốt khớp đỡ xương lưng chống nhức bó co nát"],
    usage: "**HƯỚNG DẪN SỬ DỤNG CHUẨN KHOA HỌC:**\nTuyệt phẩm quyền lực mạnh thì tuyệt đối Không Nện Dùng Nạp Dư Tràn hàng ngày phí hoang của trời sinh hóa. Mật độ uống tuyệt kỹ: 2 Cữ mỗi 1 Tuần. Uống vào trạng thái sáng Bụng Rỗng Không Mảy May 1 Giọt Sữa nào đọng lại trong bao tử để Collagen ùa cắm tự do thẳng lên bắp má đê mê hút trọn.\n\n*Nghệ thuật thưởng thức:*\nCần thái độ tôn nghiêm trịnh trọng nếm. Cầm nắp giật gắp lên chợp cắn nhai vị sâm xác đắng lởn vởn kìm vị xong mới đẩy mạnh yến mượt mụ nhè qua yết hầu rụt vào hầm tâm can.",
    tags: ["beauty", "anti-aging", "collagen", "premium", "women"],
    stock: 100,
    averageRating: 4.8,
    reviewCount: 67,
    featured: true,
    active: true,
    weight: "70ml x 1 hũ",
    origin: "Sản phẩm công nghệ Liên Doanh",
  },
];

export const mockBlogPosts: Omit<BlogPostType, "id" | "createdAt">[] = [
  {
    title: "Cách Chưng Yến Sào Đúng Chuẩn Xưa Tại Nhà",
    slug: "cach-chung-yen-sao-dung-chuan",
    content: `# Bí Quyết Chưng Yến Cách Tường: Âm Hưởng Hoàng Cung Chậm Rãi\n\nGiữa cuộc sống vội vã hối hả, có một khoảnh khắc bạn đứng lại bên gian bếp nhỏ, nâng niu đóa hoa yến trắng ngà, thả nhẹ vào thố men rạn màu lam ngọc. Chưng yến - đó không chỉ là thao tác bật bếp. Nó là một nghệ thuật tu tập tính nhẫn nại, tĩnh tâm, được truyền đời từ những yến bào chốn Ngự Thiện Phòng triều Nguyễn.\n\n## Chương 1: Đánh Thức Nữ Thần Biển (Quá trình ngâm)\nĐừng bao giờ dội nước sôi vào yến! Nó tàn nhẫn như việc phá tan những chuỗi peptide tinh túy nhạy cảm sinh học. Hãy rót nước tinh khiết ủ lạnh hoặc nhiệt độ phòng mơn man ngâm yến.\nSự chờ đợi có thể lê thê từ 30 phút đến vài giờ tùy theo độ cộm của yến thô. Nhẹ nhàng ngắm phiến yến bở tơi mềm mại, bung tỏa thành những dải lụa mỏng tang dập dềnh trong thố nước pha lê.\n\n## Chương 2: Làm Sạch Lông Mang Cả Trái Tim\nNếu đó là yến còn lông, thì chiếc nhíp tinh vi và đôi mắt điềm đạm là vũ khí. Bạn đang gạt bỏ tạp niệm của bản thân khi gắp từng chiếc lông tơ đen nhẻm vướng víu vào tơ trắng xốp. Một cái rây nếp xả trực diện dưới dòng lệ trong veo từ vòi nước sẽ giúp làm trôi sạch lớp rêu mục bám đáy yến. Rửa vừa đủ dịu dàng để không đứt ruột yến ngọc.\n\n## Chương 3: Cuộc Giao Tranh Chậm Rãi Trên Bếp Lửa\nTuyệt chiêu chưng Yến nằm ở cụm từ: **Cách Thủy Rung Động Nhẹ**.\n- Cho đóa yến no nước vào thố sứ có nắp nhỏ lọt thỏm. Đổ nước vừa xăm xắp cách đỉnh yến 1 đốt tay.\n- Đặt thố sâu vào một chiếc nồi lớn đang thầm thì reo nước hâm hấp 85 độ C.\n- Đừng để nước ngoài nồi sùng sục trào bọt tung toé, chỉ giữ lửa nhỏ li ti. Đóng nắp kín bưng để phong tỏa nhiệt hơi.\n\nKhoảng thời gian 25 - 30 phút cạn kiệt, hương tỏa thơm lừng mùi thanh thanh ngai ngái mùi trứng. Ngay lúc đó, hãy xắn hạt đường phèn Quảng Ngãi xốp rỗng rắc vào cùng vài vệt gừng thái chỉ. Đóng nắp đun sập thêm 5 phút cuối.\n\nNhấc chén ngọc ra. Đặt khẽ nếm một thìa. Một dòng ấm dẻo quánh tan lấp vào thực quản, sự thanh tĩnh của đại dương tràn ngập bao tử rỗng tuếch. Cảm ơn thiên nhiên hoang dã.`,
    excerpt: "Nghệ thuật chưng yến cung đình - Gỡ bỏ mọi sai lầm nấu nướng làm đứt gãy mạch dưỡng chất quý giá của món quà tinh túy này.",
    coverImage: "/images/blog/blog-cooking.png",
    tags: ["hướng dẫn", "chưng yến", "mẹo hay", "ẩm thực"],
    published: true,
  },
  {
    title: "10 Lợi Ích Sức Khỏe Tuyệt Vời Của Yến Sào - Thần Dược Huyền Bí Giữa Lòng Khơi Xa",
    slug: "loi-ich-suc-khoe-yen-sao",
    content: `# Phá Bỏ Nút Thắt Sinh Tử Cuộc Đời Nhờ Tinh Chất Giọt Sương Rơi\n\nXưa kia, các vua chúa vì khao khát trường sinh bất lão đã cho quân lính trèo treo leo bên vách núi dựng đứng đánh cược cả sinh mạng chỉ để mang về những chiếc tổ làm từ bọt dãi chim yến nhỏ xíu rỉ máu. Tại sao lại trả cái giá đắt nhường ấy? Hôm nay khoa học đã khám phá 10 mã gen cực phẩm bị giấu kín trong đó:\n\n## 1. Nguồn Bơm Năng Lượng Miễn Dịch Bất Bại\nAxit Sialic chiếm cực kỳ cao - đó là "bức tường khiên khiên bọc" hoàn hảo cản lại cả rổ vi khuẩn, vi trùng tấn công xâm nhập đường hô hấp mà người xưa ngợi ca là Dưỡng Vệ Khí Hoàn Mỹ.\n\n## 2. EGF - Chìa Khóa Cải Lão Hoàn Đồng Cho Phụ Nữ\nEpidermal Growth Factor - nhân tố vàng giúp lớp biểu bì tái tạo tốc độ gấp 3 lần bình thường. Chuỗi tế bào sừng chai vỡ ra, lộ làn da mỏng manh tươi trẻ tuổi 18 căng bóng mượt sương khói bay bay.\n\n## 3. Quét Sạch Phổi Giấy - Chữa Ho Viêm Ho khan\nVị ngọt thanh bình sảng khoái tính hàn của loại dãi yến đánh trực diện vào đờm nhầy kẹt sâu trong thanh quản con người, dọn dẹp sạch sẽ phế nang tổn thương sau các cơn hậu phẫu hô hấp viêm nhiễm kéo dài não nề.\n\n## 4. Nuôi Dưỡng Thánh Thể (Cho Bà Bầu)\nPhụ nữ cạn kiệt canxi thai nghén được tưới tắm lượng cực khủng Amino axit hỗ trợ bào thai tăng sinh xương chậu thần tốc từ trong bụng không mảy may gánh nặng gan thận.\n\n## 5. Đánh Rơi Stress Lên Chín Ngàn Dặm Mây Xanh\nCác chuỗi Threonine kéo não khỏi mệt mỏi cùng cực của những canh khuya mất ngủ, thả thần trí nhẹ bồng bềnh êm xui tựa dải sương mù.\n\n## 6. Món Ăn Dạ Dày Yêu Thích \nTrẻ nhỏ ốm yếu còi cọt thường đào thải thức ăn thịt cá thô rắn. Yến vào dạ dày dễ tiêu bốc khói thành tinh chất siêu vi lập tức lách qua thành ruột ngấm vào máu không tốn năng lượng tiêu hóa dạ dày bóp bao nhiêu tẹo nào.\n\n## 7. Đẩy Cửa Hồi Sinh Trí Nhớ \nPheylalanine, vi lượng đồng và kẽm thúc đẩy sự truyền dẫn qua hệ nơ-ron điện thần kinh tăng vọt - Người bệnh Alzheimer hay giới mọt sách căng não thi sẽ phải khâm phục sát bệ phóng logic bộ não khi được uống hũ yến chưng đều đặn ròng.\n\n## 8. Cứu Vương Cơ Đắp Vào Thân Mòn\nNgười sau hoá trị hóa chất độc địa, sụp cơ tay cơ cẳng - yến đưa valine và Isoleucine bồi phục lại những bó cơ bắp cứng đơ mệt rũ hồi sinh lại.\n\n## 9. Huyết Áp Yêu Dấu Nhu Hòa Lại Tim Vàng\nHạ nhiệt sự nổi loạn của những dòng máu phừng phực bơm sai nhịp tim vỡ nát, để cholesterol xấu tự động bị cuốn trôi vô thanh.\n\n## 10. Chặn Đứng Kim Đồng Hồ Oxy Hóa Nếp Nhăn\nMàng chống oxy hóa vô hình rình rập diệt gốc tự do hoành hành ngang ngược.`,
    excerpt: "Bạn đang sở hữu điều diệu kỳ gì bên trong từng chén súp trong suốt ấy? Tại sao Yến Sào lại được săn lùng ngàn năm trường kỳ?",
    coverImage: "/images/blog/blog-health.png",
    tags: ["sức khỏe", "yến sào", "dinh dưỡng", "khoa học"],
    published: true,
  },
  {
    title: "Yến Sào Cho Bà Bầu: Chặng Đường Nuôi Con Từ Trái Tim Huyết Mãnh",
    slug: "yen-sao-cho-ba-bau",
    content: `# Hành Trình Tôn Thờ Thiên Chức Nuôi Dưỡng Mần Hạt Của Mẹ Biển Cả\n\nLàm mẹ - là lúc cơ thể mong manh rút kiệt từng mẩu thanh xuân để kiến tạo nên hình dáng giọt máu lấp lánh sinh động. Nhiều bà mẹ bị bào mòn với chứng buồn nôn lả người ở kỳ thai nghén héo hắt nhợt nhạt. Tổ Yến lúc này không phải là "đồ đắt tiền chưng mua trọc phú" - mà là chiếc rễ ma mộc neo giữ sự kiên trì sinh mệnh thần thánh.\n\n## "Em Bé Thông Minh Phá Dớp - Từ Nguồn Axit Sialic"\nCác nghiên cứu khoa học Thụy Sỹ đã đổ gục thừa nhận rằng: Lượng Sialic dào dạt tích tụ trong yến đảo là viên gạch tiên phong xếp chồng thành mô cấu trúc Nơ-Ron Thần Kinh Thai Nhi Tối Đa Nhất. Ăn yến từ kỳ diệu thứ tháng 4, đứa bé cựa quậy đạp bung bụng mẹ bằng một trí não sáng rực khổng lồ tiềm ẩn. Phả hơi thở tinh khiết vào sự sống mới.\n\n## Ánh Chớp Trong Tam Cá Nguyệt Cấm Kỵ 3 Tháng Đầu\n"TIN ĐỒN HUYỀN BÍ: 3 tháng đầu mỏng manh nên không được đụng Yến tẩm bổ lạnh dạ?" \nSự thật ngã ngửa: Trong tam cá nguyệt đầu, mọi sự dập dồn xô bồ, nghén bủng rủng nôn mửa là cơn ám ảnh kinh hãi bòn rút dạ dày. Yến tính hàn lạnh - Sự khôn khéo tinh tế là hãy đun yến nhừ nát đặc kẹo lỏng với 2 lát gừng già mỏng. Một ly yến súp nóng hổi sẽ áp chế sóng dạ dày cuộn trào mà vẫn bơm được protein đỉnh của tinh túy, nạp lực mà không sợ thai lưu!\n\n## Lộ Trình Hoàn Mỹ Tuyệt Kỹ Bồi Thai:\n- Tháng thứ 4 -> Cuối tháng 7: Cứ 3 đêm ròng lại bật bếp đun 3-4 gam yến vàng ruộm chưng táo tàu ngọt lịm. Bé béo tròn bụ bẫm tăng ký cái vèo.\n- Tháng 8 -> Cận sát ngày đẻ rên la: Bà mẹ húp tổ yến đều đặn để chuẩn bị nội công vươn mình rặn đau giếng biển và hồi phục chống sa dạ con rách nát sau sanh đẻ cấp kì nhờ EGF liền mô!\n\nSợi chỉ dai giòn đó không đơn giản là thức ăn - Nó là dải băng bó dịu êm thắt chặt sợi dây liên kết máu mủ vô thời hạn.`,
    excerpt: "Sự thật đằng sau những quan niệm cấm kỵ 3 tháng đầu thai nhi. Phép màu thần đồng thông minh não bộ cho bé ngay từ lúc nằm phôi thai nôi ấm mẹ biển cả.",
    coverImage: "/images/blog/blog-pregnancy.png",
    tags: ["bà bầu", "thai kỳ", "dinh dưỡng mẹ và bé"],
    published: true,
  },
  {
    title: "Hướng Dẫn Tránh Sập Bẫy Mua Yến Gỉa Bằng Đôi Mắt Kim Giác Của Bậc Thầy Sành Ăn",
    slug: "huong-dan-chon-yen-sao-chat-luong",
    content: `# Chuyến Phiêu Lưu Trừ Tà Định Nhan Khám Phá Nghệ Thuật Chọn Yến Đỉnh Cao\n\nCầm hộp Yến giá chục triệu, cảm giác run rẩy sợ hãi nơm nớp trong ngực: "Liệu có dính bẫy nấm rong biển hồ tinh ngâm hóa chất cộp mác vua yến dối gian chăng?". Trong thương trường hỗn loạn phồn hoa này, hàng triệu tổ yến chắp vá bằng keo da bì da mủ nhan nhản khơi mào đại cục rác hôi thối. \nHãy là vị thám tử quyền uy bóc trần đường dây mánh mung này!\n\n## Mánh Mung Đội Lột Mặt Nạ "Keo Pha Túi Gói Trắng Phau"\nYến giả công nghiệp siêu ngụy trang: Người ta mua vụn vi bột yến pha dán sệt với agar rau câu, tinh bột khoai mì, thoa vuốt ve thành hình vóc cánh nôi tuyệt đẹp cứng đờ. Phơi nắng lên một mẻ "cực bóng loáng rợn người", trắng bóc vô tri mù quáng không tì vết. Ngâm vào nước 20 phút - lập tức bấy hầy vỡ tan tành hồ nhão nứt không hình hài mạch lạc.\n\n## Khai Nhãn Lực - Ánh Sáng Chắp Vá \nLấy ngay chiếc đèn pin di động soi từ ánh ngược: Nếu từng sợi xớ chằng chéo rối ren đong vào có tia tia không đều đặn vồng uốn lồng, màu hơi ố kem trứng nham nhở - Xin chúc mừng, Mẹ tự nhiên đang mỉm cười với bạn chân ái.\nCắn ngẫu nhiên 1 góc tổ khô cứng: Vị giòn vụn kêu vỡ rốp như mảnh kính xé - là yến chuẩn. Còn hơi bị bẻ dai nhách dẻo dẻo kẹo kéo uốn cạy khó khăn - Rõ ràng bị xịt đường giữ ẩm ăn gian trọng lượng chục gam nặng cân thu tiền ác liệt!\n\n## Thử Quỳ Tím - Vua Lửa Dặm Mặt Yến Yêu Ma \nTàn sát lửa khò tàn khốc: Cầm 1 ngẫu nhiên nhón nhỏ quăng bật lửa đốt. Mùi bánh gai, hồ bột khen khét lẹm mũi tro xỉ đen - yến rác giả nhựa.\nMùi đặc quánh khét cháy hữu cơ sừng lông của sừng tê nai - đấy chính là sảnh điện đanh tự nhiên của tinh hoa thật chuẩn quốc hồn quốc túy vạn vạn năm ròng.\n\nNgười tiêu dùng sành điệu là thanh kiếm thép phán quyết cuối cùng loại bỏ mọi chiêu trò trên thánh đường sức khoẻ.`,
    excerpt: "Lột trần mánh lới độn keo, ép mủ, phủ bột trắng phau tại các xưởng gia công đen tối. Trang bị khả năng soi tia thấu thị đâm thủng đồ giả lừa phỉnh ngay trong ánh mắt liếc nhìn 3 giây đầu.",
    coverImage: "/images/blog/blog-quality.png",
    tags: ["hướng dẫn", "chọn yến", "chất lượng", "cảnh báo"],
    published: true,
  },
  {
    title: "Sự Tích Huyết Yến Cùng Lời Đồn Về Giọt Máu Bi Thương Đam Mê Của Loài Chim Ngốc Lễ",
    slug: "su-tich-huyet-yen-va-loi-don",
    content: `# Tiếng Kêu Rỉ Máu Ban Đêm, Vọng Khắp Hang Sâu Lý Sơn Nước Lặng\n\nNhân gian xưa kể một trong những giai thoại xót xa và đẹp bậc nhất giới tự nhiên. Rằng loài chim Yến hằng đêm mải miết xây mạn tổ cho vợ con tị nạn gió vách cheo leo trên các hòn đảo tít tắp ngất trời. Tiết trời ác khắc bào mòn, nước bọt kiệt quệ ráo trơn. Chim bố gồng cổ họng lên nức nở khạc ho ra máu pha dãi đơm để cố gắn vá víu phần tổ nham nhở cho xong rạng rạng sáng ban mai. Những giọt huyết bầm quánh lại hằng tháng, khô nhuộm cả vạt bọt trắng ngà thành một màu đỏ thâm mận bí ẩn... \nĐó là sự mở đầu ly kỳ bi diệu về Huyền thoại Huyết Yến.\n\n## Đập Tan Mytos (Sự Thật Kế Tiếp) Khoa Học Trần Trụi Giáng Đòn \nSự thật có mĩ miều đau lòng đến chừng mực ấy không? \nThật mỉa mai lẫn thú vị: Chim Yến KHÔNG HỀ khạc rỉ máu để xịt xây tổ nào cả. Giọt máu rỉ nứt cuống họng khi kết tổ cứng dính là truyền thuyết mị dân huyễn hoặc do dân buôn thêu dệt đẩy giá Huyết Yến lên trăm triệu đồng/lạng chục phân!\n\nSân khấu thật sự xảy ra ở các hang động tối ẩm rêu xanh ngấm đá xỉ tro đen. Phân hóa học chuỗi phản ứng cực độc quyền ở dưới đáy hang mịt mù bốc lên hàm lượng Nitrit/Amoniac siêu cực mạnh bốc hơi ngấm quệ vào tảng thạch cao nơi chim bấu ngự. Vài chục ngàn năm, vạt yến trắng ngấm men hơi khí này ủ mầm lên men rực lửa chuyển sắc đổi cam thẫm rồi đỏ mận uy nghiêm.\n\n## Quyền Năng Của Sự Tái Sinh Quả Tim \nNhưng tại sao Huyết Yến (Yến Cầm Huyết) không bị phá giá đào thải?\nTuy không là giọt máu nghĩa khí bi thương, nhưng sự ủ men vách động tự nhiên tùng vạn năm đã ban cho Huyết Yến một hàm lượng sắt Oxit Iron Fe2+ siêu siêu đậm đặc ngấm lên gấp 50 lần sợi yến đảo thông thường. Yến hấp thụ linh khí thổ địa và trở thành một phương thuốc thần cường cực cường não - bổ dương và trị những chứng bệnh u thâm ung nhọt do cạn máu di truyền khốc liệt tận cốt tủy.\n\nBạn có dám uống chén yến rực đỏ này dầm chìm trong chén cổ men rạn đời nhà Minh để kết nối cùng nhịp thời gian xưa?`,
    excerpt: "Chim Yến ho lao tự khạc máu xây tổ để lại những dòng nước bọt ám ảnh đỏ quánh lộng lẫy? Đập tan màn sương mù mờ ảo và chạm đến lời giải khoa học chân ái giật mình phía sau hòn đá rêu phong Huyết Yến Tôn Quý Bậc Nhất Đế Vương.",
    coverImage: "/images/blog/blog-rednest.png",
    tags: ["khoáng thạch", "huyết yến", "truyền thuyết", "khám phá"],
    published: true,
  },
  {
    title: "Hành Trình Sinh Tử Mạo Hiểm Bước Chân Gọi Yến Về Đảo Quần Thể Lạnh Lẽo Ly Sơn",
    slug: "hanh-trinh-sinh-tu-goi-yen-dao-ly-son",
    content: `# Rơi Tự Do Xuống Rặng Đá San Hô Găm Mũi Căm - Cái Giá Của Vua Đảo\n\nGió rít bạt mạng quật từng cơn rung đứt đoạn những mảng lưới dây rợ vươn lơ lững bám vách núi dựng đứng nhọn hoắt gặm đầy lưỡi cưa rong mặn chát của đảo hoang. Đứng tận dưới này, con người chỉ là con kiến đen bám chênh vênh ở độ cao hàng chục mét xé mây mờ.\n\n## Cọng Thép Đung Đưa Và Sào Trúc Phơi Linh Hồn \nNghề thu hái vách yến đảo không dành cho người gầy thân thần kinh yếu đuối. Mỗi năm hai mùa khắc nghiệt sóng dữ bão chồm, dàn xà tre mong manh chằng chống mấp mô đóng vào khe kẽ chông chênh nham thạch đá núi. Dây thừng thắt chặt hông căng đứt lựt mạch máu cơ bụng bấu ghịt. \nNgười thợ đu người treo lơ lửng, tay cầm kẹp cong, nhãn mạn xịt xịt soi đèn pin vào sâu hút con mắt động hang tối sầm ngực lạnh lẽo tiếng dơi rít để móc từng tảng bạch ngà cẩn thận nguyên vẹn cho vào lưới vải bố đeo hông. Sảy chân - 1 giây định nghĩa vĩnh biệt!\n\n## Quyết Tâm Xây Lãnh Địa Nhử Loài Chim Lang Thang Kiêu Ngạo Trở Về Lập Tổ Dựng Xây Cộng Đồng \nLàng đảo Lý Sơn đang dần mất chim về vùng khai thác hỗn loạn khép đục. Đám thanh niên quyết chí mở sừng bám biển. Một hành trình khàn rã cổ tái thiết hang vách giả lập mọc đầy thiết bị loa sóng tần số vang nhại lại tiếng cạ xù xịt chít chít văng vọng trong đêm khuya rùng rợn thanh thanh hút hút. Ròng rã suốt 5 năm, mùi phân vương bạt chim ủ kỹ, mùi bầy đàn êm ấm sưởi lửa được giả mạn đánh bật.\n\nRồi phép màu xuất hiện! Hằng hà sa số đám bụi đen mịt trời từ đằng biển khơi xa xăm hàng hải đùn xô bay vút vào miệng hang rộng ồm oàm há hố. Quần thể phục hưng! Những sợi yến dày uỳnh phết lên mép xiềng đá lạnh lại chói dội mọc san sát.\nKhi thưởng thức chén chè yến đảo thơm lừng đặc dẻo, nào mấy ai biết đằng sau một mùi tanh man mác kiêu ngạo ấy là nước gân bắp thịt vã ra đổ mồ hôi liều cược tính phận con vượn khổng lồ trần gian hoang dại trần trụi ngoài khơi bão khốc mịt mờ!`,
    excerpt: "Cận cảnh trải nghiệm đẫm mồ hôi, sinh tử lơ lửng vách đá lưỡi cưa sâu không lối thoát để đánh cược lấy vài gam tinh chất tổ chim trong đêm tối mù khơi gió thét.",
    coverImage: "/images/blog/blog-origin.png",
    tags: ["nghề biển", "yến đảo thiên nhiên", "câu chuyện", "hành trình"],
    published: true,
  }
];

export const mockDiscountCodes = [
  {
    code: "YENSAO10",
    type: "PERCENTAGE" as const,
    value: 10,
    minOrderValue: 500000,
    maxUses: 100,
    usedCount: 23,
    validFrom: new Date("2024-01-01"),
    validTo: new Date("2027-12-31"),
    active: true,
  },
  {
    code: "FREESHIP",
    type: "FIXED" as const,
    value: 30000,
    minOrderValue: 300000,
    maxUses: 200,
    usedCount: 67,
    validFrom: new Date("2024-01-01"),
    validTo: new Date("2027-12-31"),
    active: true,
  },
  {
    code: "WELCOME20",
    type: "PERCENTAGE" as const,
    value: 20,
    minOrderValue: 1000000,
    maxUses: 50,
    usedCount: 12,
    validFrom: new Date("2024-01-01"),
    validTo: new Date("2027-12-31"),
    active: true,
  },
];

export const mockReviews = [
  { rating: 5, comment: "Yến rất ngon, sợi dày dai. Gia đình mình rất hài lòng!", userName: "Nguyễn Thanh Hoa" },
  { rating: 5, comment: "Mua làm quà biếu Tết, bao bì sang trọng, người nhận rất thích.", userName: "Trần Văn Minh" },
  { rating: 4, comment: "Chất lượng tốt, giao hàng nhanh. Sẽ mua lại lần sau.", userName: "Lê Thị Mai" },
  { rating: 5, comment: "Dùng cho bà bầu 3 tháng rất tốt, da đẹp lên nhiều.", userName: "Phạm Thị Hồng" },
  { rating: 4, comment: "Yến chưng sẵn tiện lợi, vị ngon tự nhiên.", userName: "Hoàng Đức Anh" },
  { rating: 5, comment: "Mua cho mẹ dùng hàng tháng, sức khỏe cải thiện rõ rệt.", userName: "Võ Minh Tuấn" },
];
