import { ProductType, BlogPostType } from "@/types";

export const mockProducts: Omit<ProductType, "id" | "createdAt">[] = [
  // === RAW NEST ===
  {
    name: "Yến Sào Đảo Thiên Nhiên",
    slug: "yen-sao-dao-thien-nhien",
    description: "**THÔNG TIN SẢN PHẨM**\n- Phân loại: Yến hoang dã nguyên tổ loại 1 thu hoạch trực tiếp từ hang động biển Khánh Hòa.\n- Tiêu chuẩn vệ sinh: Đạt chuẩn quốc tế, nguyên chất 100%, không độn phụ gia, không tẩy trắng, không hóa chất bảo quản.\n- Đặc điểm kết cấu: Sợi yến sụn, dệt chắc chắn, cấu trúc cứng cáp chịu được mài mòn của gió biển.\n- Giá trị dinh dưỡng: Giữ nguyên tối đa hàm lượng Protein, 18 loại Axit amin và kẽm vi lượng thiết yếu.\n\n*Câu chuyện sản phẩm:*\nBên những vách đá dựng đứng của hòn đảo ngọc tít tắp khơi xa, nơi quanh năm đón gió biển mặn mòi và những con sóng tung bọt trắng xóa, loài chim yến hoàng gia đã dệt nên những tổ yến diệu kỳ. Yến Sào Đảo Thiên Nhiên là kết tinh của đại dương mênh mông, mang giá trị dinh dưỡng cao nhất, là món quà quý giá bồi bổ nguyên khí vượt thời gian.",
    shortDescription: "Tổ yến hoang dã khai thác từ đảo Khánh Hòa. Sợi yến sụn dày, nguyên chất 100%, không hóa chất mài mòn.",
    price: 2800000,
    originalPrice: 3200000,
    images: ["/images/products/raw-island-1.png"],
    category: "RAW",
    benefits: ["Bổ sung dinh dưỡng toàn diện, phục hồi sức khỏe nhanh", "Hỗ trợ tiêu hóa, làm sạch hệ hô hấp vòm phổi", "Chứa nhiều khoáng chất kẽm, canxi bồi bổ cơ bắp và xương khớp", "Giúp cải thiện làn da từ sâu bên trong cơ thể"],
    usage: "**HƯỚNG DẪN SỬ DỤNG CHUẨN KHOA HỌC:**\n- Bước 1 (Ngâm nở): Đặt tổ yến vào bát nước sạch, ngâm từ 3 đến 4 giờ cho đến khi các sợi yến tơi hoàn toàn.\n- Bước 2 (Rút lông): Dùng nhíp chuyên dụng loại bỏ tạp chất và lông tơ. Tráng nhẹ qua rây tránh làm sợi nát.\n- Bước 3 (Chưng cách thủy): Đun nhỏ lửa ở nhiệt độ không quá 85°C trong 30-35 phút. Để yến không bị chai dòn, chỉ cho đường phèn vào đúng 5 phút cuối.\n- Định lượng tiêu chuẩn: 3-5 gram/lần cho người lớn, 1-2 gram/lần cho trẻ nhỏ.\n\n*Nghệ thuật thưởng thức:*\nKhi chén yến còn nghi ngút khói ngai ngái hương vị của biển, hãy tĩnh tâm thưởng thức chậm rãi từng ngụm nước dẻo quánh thanh mát. Không gì tuyệt vời hơn lúc này là để năng lượng thuần khiết đánh thức các tế bào đang mỏi mệt trong cơ thể bạn.",
    tags: ["premium", "island", "natural", "gift"],
    stock: 50,
    averageRating: 4.8,
    reviewCount: 45,
    featured: true,
    active: true,
    weight: "100g",
    origin: "Khánh Hòa, Việt Nam",
  },
  {
    name: "Yến Sào Hang Cao Cấp",
    slug: "yen-sao-hang-cao-cap",
    description: "**THÔNG TIN SẢN PHẨM**\n- Phân loại: Dòng Yến hoang dã siêu cấp khai thác từ vách thạch nhũ hàng trăm năm tuổi tại Bình Thuận.\n- Đặc trưng hóa học: Hấp thụ gốc Sắt (Fe), Kẽm (Zn) và Mangan tự nhiên, làm cho cấu trúc ngả mầu vàng cam nhẹ đặc thù.\n- Điểm mạnh chuyên biệt: Sở hữu nồng độ Sialic Acid và oxy hóa cao vượt ngưỡng thông thường, dành riêng cho tạng người suy kiệt nặng.\n- Tiêu chí khắt khe: Tỷ lệ tồn tại khá hiếm hoi, đòi hỏi quy trình nhặt lông hạn chế nước nồng độ cao để không hòa tan khoáng chất.\n\n*Câu chuyện sản phẩm:*\nSâu thẳm trong những hang động rêu phong, nơi ánh sáng hiếm hoi chiếu xuyên qua kẽ đá hẹp, loài Yến cổ đại dệt nôi trên những thạch nhũ rỏ nước. Hàm lượng vi lượng đất khoáng rỉ rả ngày qua ngày đã nhuộm tổ yến bằng sắc độ vàng trầm tích. Đó chính là một liều linh dược cô đặc mà Mẹ tự nhiên đã ban tặng.",
    shortDescription: "Tổ yến hoang dã trăm năm từ hang thạch nhũ. Hàm lượng khoáng vô biên, siêu hồi phục, siêu phục hồi.",
    price: 4500000,
    originalPrice: 5000000,
    images: ["/images/products/raw-cave-1.png"],
    category: "RAW",
    benefits: ["Sở hữu chỉ số vi khoáng cực cường từ vách hang đá", "Hồi sức cấp tốc cho người suy nhược nặng", "Nâng cấp cực lớn rào chắn hệ hệ miễn dịch"],
    usage: "**HƯỚNG DẪN SỬ DỤNG CHUẨN KHOA HỌC:**\n- Bước 1 (Ngâm nở hóa mềm): Do chứa lượng chất khoáng cứng, cần ngâm nước sạch lâu hơn, khoảng 4 đến 5 tiếng liên tục để bở tổ yến.\n- Bước 2 (Chưng cách thủy): Không dùng lửa để dội trực tiếp. Hấp nhiệt lượng nhỏ hơn 85°C tối đa trong 40 phút.\n- Bước 3 (Hòa quyện dược thảo): Cực hợp khí huyết khi mix thêm Táo Đỏ gieo hạt, Tuyết Nhĩ hoặc hạt Kỷ Tử ở 10 phút sau cùng.\n- Cảnh báo: Tuyệt đối không dùng bình siêu tốc rót nước sôi thẳng vào yến khô gây nổ gãy tế bào khoáng chất.\n\n*Nghệ thuật thưởng thức:*\nHương thơm dai nhách và mùi thơm thô mộc của Yến hang rất rõ rệt. Cách dùng đỉnh đạc nhất là bưng bát gốm sứ từ từ lách sợi vào cuống não sảng khoái đánh bật những sự trống rỗng trong tâm hồn.",
    tags: ["premium", "cave", "rare", "health"],
    stock: 20,
    averageRating: 4.9,
    reviewCount: 28,
    featured: true,
    active: true,
    weight: "100g",
    origin: "Bình Thuận, Việt Nam",
  },
  {
    name: "Yến Sào Lông Nguyên Chất",
    slug: "yen-sao-long-nguyen-chat",
    description: "**THÔNG TIN SẢN PHẨM**\n- Phân loại: Dòng tổ yến nguyên bản (Raw Material), bảo toàn 100% hình thể ban sơ ngay khi mới cắt khỏi vách nôi yến.\n- Đặc điểm cấu trúc: Chứa lẫn một phần lông vũ li ti, hạt dăm trứng dãi vương vãi, minh bạch tối đa độ trung thực của sản phẩm.\n- Tối ưu hóa màng sinh học: Vì chưa từng qua nhúng nước xử lý nhà máy, lớp bảo vệ Enzyme bề mặt yến không bị cuốn trôi.\n- Giải pháp đầu tư: Giá thành cực rẻ do cạn kiệt chi phí gia công thủ công, phù hợp mua tích trữ sử dụng tại định mức chi tiêu gia đình hằng tháng.\n\n*Câu chuyện sản phẩm:*\nVẻ đẹp của sự thô ráp chân thật! Lựa chọn Yến lông là lựa chọn đối mặt trực diện với món quà nguyên sơ nhất, không chải chuốt bề mặt. Giống như tình thương tảo tần của thế hệ trước, việc kiên nhẫn cúi người lựa từng mảng tơ đen nhách để trả lại ánh sáng cho một mảng yến ngọc trắng muốt là thước phim đong đầy sự cảm mến tự thân.",
    shortDescription: "Tổ nguyên bản không vệ sinh cơ học, giữ 100% mùi nguyên thô của nhà yến thiên nhiên hoang dã.",
    price: 1800000,
    originalPrice: 2200000,
    images: ["/images/products/raw-feather-1.png"],
    category: "RAW",
    benefits: ["Bảo vệ trọn vẹn lớp bề mặt tế bào yến nhạy cảm với nước rửa công nghiệp", "Minh bạch 100% về độ thật của sản phẩm", "Tối ưu hóa giá thành do giảm chi phí dịch vụ làm sạch thủ công"],
    usage: "**HƯỚNG DẪN SỬ DỤNG CHUẨN KHOA HỌC:**\n- Bước 1 (Giai đoạn nhặt rác): Chuẩn bị một bếp nhíp gắp đầu bén chuyên dụng và bát nước nhỏ. \n- Bước 2 (Giãn yến): Trải dải yến ngâm trong nước từ 2-3 tiếng để các nang tổ bung cấu trúc ra, sợi lông tự rời rụng.\n- Bước 3 (Lọc tơ): Gắp các sọc lông chính yếu, rồi nhúng nhẹ chiếc yến qua rây nước lọc tới khi thanh trùng không còn điểm dăm đen.\n- Ghi chú: Một mảng yến nhặt mất tầm 20-30 phút thao tác tập trung.\n\n*Nghệ thuật thưởng thức:*\nThưởng thức yến lông vừa rửa tại nhà giúp lan tỏa vị tanh mộc mạc y hệt mùi sương biển khơi dạt dào ấp vào lòng. ",
    tags: ["natural", "affordable", "health"],
    stock: 80,
    averageRating: 4.5,
    reviewCount: 62,
    featured: false,
    active: true,
    weight: "100g",
    origin: "Nha Trang, Việt Nam",
  },
  {
    name: "Vụn Yến Sào Tự Nhiên",
    slug: "vun-yen-sao-tu-nhien",
    description: "**THÔNG TIN SẢN PHẨM**\n- Phân loại: Dòng Yến sợi cắt, vỡ nhỏ được bóc tách từ quy trình mài gọt, tinh chỉnh góc cạnh của tổ yến hạng A.\n- Độ tương đương sinh hóa học: Đảm bảo 100% lượng C, H, O, S và N y chang dòng yến thượng lưu, chất lượng Protein bảo toàn nguyên trạng.\n- Đặc điểm cơ lý học: Sợi xốp, mảng mỏ xé dẹt, cực kì dễ ngậm nước và không yêu cầu dạ dày nhai nuốt lực mạnh.\n- Ưu điểm siêu việt: Giao cắt lợi ích chi phí cao nhất, hỗ trợ tốt cho đối tượng có hội chứng kén ăn, tắc thanh quản.\n\n*Câu chuyện sản phẩm:*\nVụn Yến là những vóc ngọc nhỏ bị phân cách ra khỏi cấu trúc liền khối trang trọng, mang theo tấm lòng thiết thực khiêm nhường. Không cần ngoại hình đắt đỏ hoàng kim, vụn yến sinh ra để len lỏi âm thầm vào bát cháo ăn dặm mỗi sáng của con thơ hay trở thành nụ cười khỏe khoắn trên môi người mẹ lớn tuổi khi tính toán một ngân sách gia đình thông minh mà khéo léo.",
    shortDescription: "Giá trị bổ trợ từ mảnh vụn hữu ích, dinh dưỡng tinh hoa y chang dòng cực phẩm. Lựa chọn chi tiêu lý tưởng thông minh.",
    price: 900000,
    originalPrice: 1200000,
    images: ["/images/products/raw-broken-1.png"],
    category: "RAW",
    benefits: ["Tiết kiệm đáng kinh ngạc cho bữa tẩm bổ hằng ngày", "Dễ dàng ngấm và xay nhuyễn cực tốt cho trẻ biếng ăn cần nhai nuốt nhẹ", "Tránh việc xài phí nguyên mảng to vượt cỡ"],
    usage: "**HƯỚNG DẪN SỬ DỤNG CHUẨN KHOA HỌC:**\n- Bước 1 (Ngâm chớp nhoáng): Nhờ bản chất sợi mảnh vỡ tơi xốp, chỉ tốn 15-20 phút ngâm trong đồ sứ là chậu đã nở ngậm nước ráo xòa.\n- Bước 2 (Pha chế đa dụng): Nếu nấu kèm Súp hoặc Cháo, đun thịt xương tơi rục chín hẳn ra mâm rồi mới rưới dải hạt vụn Yến lên, phủ nắp đậy trong 5 phút.\n- Cảnh báo bảo lưu: Độ dãn vỡ khiến vụn không chịu được mức lửa cách thủy lâu dài. Không chưng dài vượt mức 20 phút.\n\n*Nghệ thuật thưởng thức:*\nVụn yến mềm mịn xốp xượt không dai như yến nguyên tảng to nhưng dễ mút tụt ực phát qua thực quản nuốt nhẹ tênh dỗ dành dạ dày tổn thương khốc liệt nhất của người bệnh lớn tuổi.",
    tags: ["affordable", "daily", "family"],
    stock: 150,
    averageRating: 4.3,
    reviewCount: 89,
    featured: false,
    active: true,
    weight: "100g",
    origin: "Nha Trang, Việt Nam",
  },

  // === REFINED ===
  {
    name: "Yến Sào Tinh Chế Trắng",
    slug: "yen-sao-tinh-che-trang",
    description: "**THÔNG TIN SẢN PHẨM**\n- Phân loại quy trình: Dòng Yến ép khuôn thuyền ngà truyền thống, dọn sạch lông 100% tại nhà máy kiểm định tiêu chuẩn ISO khép kín.\n- Phương pháp tinh lọc: Sử dụng gắp vi lượng cơ học kết hợp rây siêu màng nhuyễn, tuyệt đối cự tuyệt sử dụng hóa chất Javen để tẩy ngà.\n- Thành phần nguyên khối: 60% dệt thân sợi tơ dọc liên kết dẻo bện, 40% khối vụn ruột màng chân đế yến gia cố bên dưới.\n- Chứng nhận uy tín: Sản phẩm 0 vi nấm rác thải, có thể đưa vào công đoạn nấu chín lập tức ngay sau khi xé nhãn mở hộp.\n\n*Câu chuyện sản phẩm:*\nĐược nhào nặn dưới đôi bàn tay điêu luyện của hơn 50 nghệ nhân lâu năm ròng rã hàng chục giờ - Yến Sào Tinh Chế Trắng mang trong mình vẻ đẹp xuất sắc của một nàng thơ tuyết bay bổng lướt mượt qua vòm kính. Nó là giải pháp cực kỳ tốc chiến tôn vinh vẻ thanh lịch của giới tinh hoa bận rộn.",
    shortDescription: "Sạch sẽ 100%, dệt khuôn thuyền nhã vặn, sẵn chế biến ngay không dây tạp khuẩn nào. Giải pháp Quà Biếu hạng A.",
    price: 3500000,
    originalPrice: 4000000,
    images: ["/images/products/refined-white-1.png"],
    category: "REFINED",
    benefits: ["Tiết kiệm vĩnh viễn quỹ thời gian chế biến gắp rửa dọn lông nan giả nhái", "Sợi dệt liên kết dài, tạo thị giác mãn nhãn cao quý cúng tế biếu người", "Giữ nguyên nồng độ Protein gốc nguyên hạt"],
    usage: "**HƯỚNG DẪN SỬ DỤNG CHUẨN KHOA HỌC:**\n- Bước 1 (Tráng đục nhanh): Do tổ yến đã làm khô tiệt trùng rút cạn nước, bạn chỉ cần gắp yến dội ngâm đẫm tầm 25-30 phút là đã tung rẽ sợi mượt.\n- Bước 2 (Chưng cách thủy nhiệt đều): Chuẩn bị nón cách nước, ninh đậy lồng trong nửa tiếng với độ nóng êm phớt (80°C).\n- Thảo mộc kèm theo: Cực kì hợp khi nhỏ một lớp vài giọt gừng mật, đính kèm quả ngân nhĩ sen chè hoàng cung thanh đạm.\n\n*Nghệ thuật thưởng thức:*\nSợi dệt của Yến Trắng có độ quyện dai nẩy bật. Gợi ý bạn hãy thực hành một nồi Chè 'Lục Phẩm Tiến Vua' với Bạch quả, Hạt Chia vàng, Tuyết Nhĩ ngâm mộc, Táo đỏ khô... Cảm nhận 1 buổi ăn tráng miệng xa xỉ thanh cao.",
    tags: ["premium", "clean", "gift", "convenience"],
    stock: 60,
    averageRating: 4.7,
    reviewCount: 56,
    featured: true,
    active: true,
    weight: "100g",
    origin: "Ninh Thuận, Việt Nam",
  },
  {
    name: "Sợi Yến Vàng Cao Cấp",
    slug: "soi-yen-vang-cao-cap",
    description: "**THÔNG TIN SẢNগঠ**\n- Cấp bậc phẩm chất: Hạng mục hiếm hoi của các chim Yến già cỗi đời 10-15 năm tuổi nhả gen vi khoáng bọc thép vào mút tổ.\n- Đặc thù khoáng mạch hóa học: Được lai tạp nồng độ cao Oxit Kẽm (Zn) và phân tử Sắt (Fe++) sinh học khiến sợi dãn dày mập cục, sần sật và bật tông vàng đồng lấp lánh nguyên sơ kén nhái.\n- Tỉ suất khai thác: Chạm ngưỡng cực thấp, chiếm bé hơn định suất 5% ở hệ thống hang đảo thu hoạch mỗi khi vào đông.\n- Dược tính hỗ trợ: Là ngòi pháo mồi cực mạnh cho sự vận chuyển lưu thông hồng huyết cầu và hỗ trợ dẻo dai thành gân tế bào.\n\n*Câu chuyện sản phẩm:*\nNếu Yến Trắng là Nàng thơ tuyết mơ màng thì Sợi Yến Vàng chính là Nữ hoàng mặt trời cháy nắng vinh quang rực rỡ. Rất hiếm hoi tự nhiên chịu nhả ngọn hoàng kim vào chiếc vòm hốc ẩm, biến chất lỏng trắng tinh khiết thành hòn quặng dẻo kẹo dai nhách ánh nhũ vô nhị cực sành cực kén. Nhâm nhi nó là xác nhận vị thế am tường đắt kỷ khó nhằn của dân tinh anh.",
    shortDescription: "Quặng Hoàng Kim siêu dai giòn hiếm có, hấp thụ oxit kẽm khoáng dồi dào, hàm lượng bổ rực sức chiến binh sống dai.",
    price: 5200000,
    originalPrice: 5800000,
    images: ["/images/products/refined-golden-1.png"],
    category: "REFINED",
    benefits: ["Nâng lượng rực rỡ sản sinh mô tạo máu đỏ oxy cao nhất", "Thương vị nồng đặc đậm khó xoáy nhầm qua dòng thô mộc xơ nhạt", "Duy trì thanh xuân da thịt săn dẻo chắc"],
    usage: "**HƯỚNG DẪN SỬ DỤNG CHUẨN KHOA HỌC:**\n- Bước 1 (Giải khóa mạch sợi): Sợi yến rễ vàng rất lì đòn bền bỉ. Mức thời gian thúc phồng mạch kéo dãn tối thiểu 45 - 50 phút.\n- Bước 2 (Chưng đôi nhịp lửa): Mở mức cách thuỷ 15 phút ban đầu cho lửa trung bình nhồi cho bung sụn dẻo kẹo, sau đó 15p cuối bóp nhỏ lửa râm ran ninh đường nạo thấm nhuyễn.\n- Hạn độ dùng: Người mang thai mỏi kệt và người vừa sau thủ thuật mổ y tế xương gân được khuyên ưu tiên tuyệt đối hạng mục này.\n\n*Nghệ thuật thưởng thức:*\nMùi tanh biển rất trầm dày cuốn quýt dai xộc. Yến râm nảy độ giòn tanh tách khi cắn chạm vỡ trên hàm nha làm xiêu lòng bao tay sành chấn động. Dùng với ít hạt sen non tươi ninh luộc chín trước để bổ âm toàn diện tủy mạch.",
    tags: ["rare", "premium", "golden", "mineral"],
    stock: 15,
    averageRating: 4.9,
    reviewCount: 19,
    featured: true,
    active: true,
    weight: "50g",
    origin: "Khánh Hòa, Việt Nam",
  },
  {
    name: "Yến Nhỏ Cho Bé",
    slug: "yen-nho-cho-be",
    description: "**THÔNG TIN SẢN PHẨM**\n- Cơ chế đối tượng màng bọc: Thiết kế bẻ ngắn sợi dọc, tập trung dải ruột sườn của chim Yến (hạt nhỏ xốp li ti) êm viễn vào niêm mạc trẻ trâu hóc kẹt.\n- Thông số khuôn đúc nón: Ép dệt thành hàng đồng xu định mức gram nhẹ chuẩn (1.5 - 2.0g/viên). Tránh cân đo chi li thủ công ở mẹ bỉm.\n- Thông tin hóa thực nghiệm: Bổ trợ vi axit sialic thúc đẩy nơ ron thần kinh ghi nhớ kết dính tế bào của trẻ từ 12-48 tháng tuổi.\n- Xác nhận độ an toàn: Máy tia UV tiệt diệt nấm sừng, không tẩm chất độn rong agar làm nhái để nhồi bụng nghẽn tắc táo bón bé mầm.\n\n*Câu chuyện sản phẩm:*\nYến Nhỏ Cho Bé mang trọn trái tim của tình mẫu tử và sự thấu cảm rưng rưng. Một viên yến nhíu nhéo trắng tuyết vo tròn cúc áo tưởng chừng mong manh nhưng khi thả vào cháo húp nở toè xòe mây trắng tinh là cứu tinh đánh đuổi cơn khóc bực biếng ăn còi cọt còi nhẵng xương tay bần thuồng luồng. Nó là lời hứa vô thanh mạnh mẽ nụ cười bảo chứng cân nặng mũm mĩm tương lai.",
    shortDescription: "Đồng xu yến nhỏ mềm tơ cắt khúc siêu cấp phù hợp niêm mạc trẻ trâu ấu, tăng cao hàm kháng sinh tự nhiên siêu khuẩn.",
    price: 2000000,
    originalPrice: 2400000,
    images: ["/images/products/refined-baby-1.png"],
    category: "REFINED",
    benefits: ["Tan vỡ mịn mượt, đẩy mạnh chuyển hóa không ngâm đầy hơi chướng căng bụng", "Chuẩn khẩu phần 1 lần ăn không cần trĩu cân tiểu li rạch rách bao", "Nuôi nền đề kháng xưng phổi tị mũi siêu cường đại"],
    usage: "**HƯỚNG DẪN SỬ DỤNG CHUẨN KHOA HỌC:**\n- Hạn mức tiêu nạp chuẩn: Đối với chu kì lứa tuổi 1-3, bóc nhẽ và dùng định mức nửa nón / 1 nón nhỏ (1.5g) cách 2 ngày chưng 1 nhịp.\n- Bước 1 (Ngâm tan bọt): Vì tính chất hạt xốp đặn ngắn ngủi, nhúng nước rã ầm chỉ tốn khoảng 15 phút là yến trào trạt bung tơi tựa rễ liễu đệm.\n- Bước 2 (Chống sốc gia vị): Hạn chế thêm ập đường cát cho trẻ em 1 tuổi trớ lợm cổ họng ngái. Chỉ hấp mềm dũa 15 phút và tắt rịt.\n- Trộn dinh dưỡng xen ngang: Rắc nhẹ hỗn hợp hạt nhuyễn này vào tô nhuyễn cháo óc heo, hoặc bột gạo sữa quấy để che lấp mùi biển sầm tanh nhè nhẹ.\n\n*Nghệ thuật thưởng thức:*\nKẻ sành nhất hãy khuấy xay nhẹ ngô non vàng luộc chín thành súp kem cốt pha vào yến nhuyễn trong lúc bé chóp chép. Hương ngô vàng chanh ngật ngào xua tanh tưởi bọt khiến trẻ mê li hút tụt hạt cặn chóp tận hớp muỗng cuối.",
    tags: ["baby", "safe", "immunity", "brain"],
    stock: 70,
    averageRating: 4.6,
    reviewCount: 73,
    featured: false,
    active: true,
    weight: "50g",
    origin: "Việt Nam",
  },
  {
    name: "Hộp Quà Yến Sào Premium",
    slug: "hop-qua-yen-sao-premium",
    description: "**THÔNG TIN SẢN PHẨM**\n- Phân khối hiện vật: Combo cao cấp gọng cứng hội tụ đa dạng sắc diện. Vỏ ép mủ vân gấm UV dập chìm chống ẩm sần sang trọng lót gối nệm chịu quăng đập chuyển phát.\n- Cấu trúc phẩm tạng combo: Tổ hợp bộ đôi chiến binh gồm 1 khay Yến Tinh Chế Trắng nguyên khối dệt cườm xấp xỉ 100gr kèm hộp quà mica; + Bổ trợ cặp uyên ương 2 Hũ Yến Thủy Tinh vô trùng đã chưng ngấm nguyên nhũ nắp vặn ánh kim vàng 70ml.\n- Trị giá cốt lõi: Nâng tấc thẩm mỹ trao đổi thương quyền ngoại giao, thấu đáo trọn tâm can lễ tiết ở cung cách tặng biếu Sức khoẻ sinh học không rập khuôn.\n- Chứng từ uy tín ngầm: Toàn vẹn kèm phụ kiện kẹp tặng chổi nhíp vàng đồng, mâm táo đỏ mọng, và phiếu cẩm nang minh xác cam kết xuất xứ.\n\n*Câu chuyện sản phẩm:*\nViệc trao món Yến Sào đại diện cho lời nguyền sinh mệnh chúc 'Phúc Thọ An Khang'. Hộp quà nới ra trước mắt như một mật điện uy mãnh triều nguyên hoàng đế cung phụng mẫu nghi. Sự phối hợp vừa được chứng thực qua món nhấp tươi sảng khoái liền mạch vừa ngâm vóc yến chưng dài tự tại khẳng định trọn thành ý sâu nẳm không vụ lợi mà tràn chàn ân sủng nết hiếu thảo.",
    shortDescription: "Combo Lễ Nghi Uy Mãnh VIP Thượng Đỉnh chốt hạ dâng tặng ngoại giao - 100g Yến trắng ép cườm & 2 Hũ ngọc rót rực.",
    price: 4800000,
    originalPrice: 5500000,
    images: ["/images/products/refined-giftbox-1.png"],
    category: "REFINED",
    benefits: ["Nâng tầm giá trị ngoại giao biểu dương phô bày bộ sưu tập cực phẩm", "Cam kết set quà vẹn toàn đủ táo đỏ/đường cung cấp", "Thiết thực tiện nghi hai đường lối: Dùng ngay hoặc Tự nấu vui thảnh thơi"],
    usage: "**HƯỚNG DẪN SỬ DỤNG CHUẨN KHOA HỌC:**\n- Hướng mục sản phầm 2 Hũ Chưng: Xoay lẫm nắp ngược chiều khóa áp lực an toàn. Bật nắp hơi ực tiếng bốp chân không là thành công. Uống tu ngập dạ ngay không khựng nhịp chờ hâm. Đổ tử đông mát lịm 10 hút nếu cần giải lốc hỏa ngục trời chiều.\n- Hướng mục 100G tổ Cườm sấy khô: Phân mảnh bảo lưu ở bóng tối khô ráo, lồng kính thoáng, bưng né xa luồng hẻm máy hút ẩm ẩm thấp.\n- Công du trình diễn: Tốt nhất rước trọn hộp dộng thẳng tới mâm cổ tặng ông bà ngoại giao trực tiếp bằng nhãn tiền rực sáng của nệm lót kim sa hoàng miện.\n\n*Nghệ thuật thưởng thức:*\nSử dụng phụ kiện thiệp mạ kim đính ở mép góc xô lụa viết nắn viền chữ tri ân gửi phụ mẫu bề trên để khai thông hoàn bị sự sung tức nghi thức báo hiếu kính túc bành tổ thiên hạ.",
    tags: ["gift", "premium", "combo", "holiday"],
    stock: 30,
    averageRating: 4.8,
    reviewCount: 34,
    featured: true,
    active: true,
    weight: "Combo 100g khô + 2 hũ chưng",
    origin: "Việt Nam",
  },

  // === READY TO EAT ===
  {
    name: "Yến Chưng Nhân Sâm",
    slug: "yen-chung-nhan-sam",
    description: "**THÔNG TIN SẢN PHẨM**\n- Phân loại kỹ thuật: Dạng yến chưng đúc tiệt trùng đậy khối Paster dưới nền luồng áp lực bọt khí, hũ yến tươi thủy tinh.\n- Tích hợp linh dược: Lượng yến mật đặc dêt tỉa ngấm trên dung dịch chiết tủy từ Nhâm Sâm Tươi Hàn Quốc gân củ 5 năm kinh niên trồng thổ sinh học siêu cường.\n- Định hướng hiệu năng: Tương quan rực rỡ khí huyết tạng, đẩy xông máu vọt lùi chán kiệt tâm can nhồi óc u oải, bứt phá sức mạnh cơ bắp cho đàn ông lão hóa nhanh.\n- Thiết lập chuẩn ISO bảo an: Không xài axit hoá chất ướp nấm ngăn men độc thủ công. Tuyệt đối dập nắp ép nén kín vi khuẩn chết không phôi sinh rêu bào ở hũ ngập cạn.\n\n*Câu chuyện sản phẩm:*\nKhi mà nhịp sống khốc liệt của đô hội đẩy bật thân xác xuống mỏi mệt cực điểm uề uải chán nản váng đầu, vị thuốc đại thần Nhân Sâm hòa lướt dẻo quánh cùng Yến tinh chất hất tông lên hương rượu nồng ấm ức chát rát hăng tạc dạ. Nó vọt xoáy sự nứt gãy cơ trướng và đẩy xông dòng lửa bừng phực ấm lòng nội tạng.",
    shortDescription: "Giam giữ Sức Ấm Đại Dương & Linh Khí Rễ Hồng Sâm 5 Tuổi bừng bừng sức mạnh sống bứt phá khỏi tụt ức váng mệt.",
    price: 180000,
    originalPrice: 220000,
    images: ["/images/products/readytoeat-ginseng-1.png"],
    category: "READY_TO_EAT",
    benefits: ["Hồi đáp sinh dực, phực nhãn sức đờ đoái lao tâm", "Phục cường làm trơn tru cọ xoáy xua đuổi phong hàn tà lạnh ướt người", "Tiện ích thần sầu húp một giây xong chuyện bổ 3 ngày dai"],
    usage: "**HƯỚNG DẪN SỬ DỤNG CHUẨN KHOA HỌC:**\n- Bước 1 (Giao động phân kỳ): Cầm lốc xoay nhún lọ theo cổ xoáy tay nhẹ nhàng 5 giây để lớp sâm bột và nhũ yến kẹo quánh không giề đóng đặc ở lúp nắp hay đáy chai chìm nghỉm.\n- Bước 2 (Giờ phong tỏa): Khắc ngự hoàng điểm kim để hút ực hũ sâm hắc đại cường này là tít 8H - 10H SÁNG sau thức mộng ru.\n- Cảnh báo sức đỏ: TUYỆT ĐỐI NGỪNG sực nốc vô buổi tối trước giường đi lịm tâm vì Nhâm Sâm chọi yến găm bốc nhiệt hỏa huyết phá lồng ngực làm mở mắt trao cháo khó thiếp vùi giấc thâu trần chọc.\n\n*Nghệ thuật thưởng thức:*\nCó thể thả ngâm cả lọ vô bát nước nóng ấm sùng sục 10 phút sau đó mới mở cho dòng lưu nóng sâm kích bốc vị hương khốc liệt nghẹt mũi tỏa mùi nam nhi chí nam vương đại hùng tráng.",
    tags: ["convenient", "ginseng", "health", "daily"],
    stock: 200,
    averageRating: 4.6,
    reviewCount: 124,
    featured: true,
    active: true,
    weight: "70ml x 1 hũ",
    origin: "Việt - Hàn Hợp Tác",
  },
  {
    name: "Yến Chưng Đường Phèn",
    slug: "yen-chung-duong-phen",
    description: "**THÔNG TIN SẢN PHẨM**\n- Phân phối cơ chất: Dòng Base tinh nhã nền gốc y học cổ mộc miên truyền đời hoàng triều. Hàm lượng cố định 10% sợi Yến cườm thật sự móc lúp cùng dung dịch đường phèn.\n- Tính chất vật lý đường tinh luyện: Phèn kết tủa góc chỏm lục địa Quảng Ngãi vắt tinh trong nản 18 độ cữ giòn đanh bồng bềnh uốn mật, vạch định hàm lượng thấp tránh thuyên đái đường mỏi họng gắt chua rít đắng.\n- Độ kiểm định khang lọc: Chế kỹ thuật hấp Paster áp suất chân không nhiệt cao giệt chủng 100% nấm lốc xoáy rêu mục mà vẫn tạo kết dính hũ thuỷ tinh trắng nhòa thanh tâm không cặn dặm nát vẩn đục bụi.\n- Giá thành hợp ví tiền: Nguồn yến nạp bổ cữ cơ dọc hằng này duy trì êm ấm bền bỉ dài hơn.\n\n*Câu chuyện sản phẩm:*\nTrong một thế giới đầy những gia vị pha tạp chế lấp mặn chua, Yến chưng đường phèn đứng vững chãi vĩnh cửu như một bức tượng đài Tối Giản Mộc Miên thuần bạch dạt dào êm ả mộng. Ẩn mình sau lớp vỏ hũ nắp vàng khiêm tốn là vị ngòn ngọt lợt lẻo thanh bồng bềnh uốn xoa xịu vòm lăm rát xơ ho.",
    shortDescription: "Chén mộc nước thanh phèn trôi vèo thanh tân y tế chơn láng mọi vết rát ho vòm xưng cúng kiến nội tạng trẻ lại.",
    price: 150000,
    originalPrice: 180000,
    images: ["/images/products/readytoeat-sugar-1.png"],
    category: "READY_TO_EAT",
    benefits: ["Tiêu giảm nội hỏa cháy bừng phổi viêm sặc họng đớn", "Hóa thạch cơn khát kiệt trạc hạ nhiệt cơ trơn láng bóng mĩ dạ mỏng bọc", "Tiện ghim xài húp lót trẻ non mẹ gầy bụng lả u"],
    usage: "**HƯỚNG DẪN SỬ DỤNG CHUẨN KHOA HỌC:**\n- Thao tác đóng mở: Mở chốt niêm chì xoáy bật vặn dùng tức thì vô hiệu. \n- Xếp dọn cấp đông: Khi mang đi biếu cho tặng có thể quăng ngay vô thềm lốc đá ngăn mát quạt dưới 10°C để ốp the rinh ranh nhấp môi tê dại quánh nẩy hạt ngon xoắn nẻo.\n- Khung giờ mồi kim chỉ: Rốc luôn vạt 1 chai cữ nhẹ này vào khung 9h-10h tối giáp ranh ngủ nhắm mí để xoa dịu mệt tuệ ru êm mềm dạ trơn luột tiêu êm xoa ngực đờm ho ru sâu cạn giấc đi thiếp nín tiếng mộng não.\n\n*Nghệ thuật thưởng thức:*\nHãy dùng chiếc muống gốm sứ múc gảy miết lốc từng bụp Yến quánh đường thanh lên vòm niêm mạc lưỡi, nhắm mắt xuôi văng để cặn sụn trượt êm mềm không dại gì dốc lọt luốt òng ọc kẻo vụt nhoát qua phí hoài.",
    tags: ["classic", "convenient", "family", "daily"],
    stock: 300,
    averageRating: 4.5,
    reviewCount: 156,
    featured: false,
    active: true,
    weight: "70ml x 1 hũ",
    origin: "Ninh Thuận",
  },
  {
    name: "Yến Chưng Nước Dừa",
    slug: "yen-chung-nuoc-dua",
    description: "**THÔNG TIN SẢN PHẨM**\n- Phân luồng dược phẩm sinh hóa: Giải pháp cực khoái thanh nhiệt trộn lẫn hoàn mỹ Yến sào nguyên tổ băm xé 15% cuộn rẽ lớp màng ruột với cốt trái Xiêm lùn Bến Tre ngọt lịm mộc mạc.\n- Hiệu ứng kép xúc tác: Luồng I-on khoáng Magie cực hỏa tốc của dừa bơi len lách vô vi phân sợi collagen yến ép đùn sức mạnh nhân đôi kéo điện giải mồ hội khô quắt dẻo ra 1 mẻ.\n- Màu vị cảm quan: Hơi men chua chua thơm lừng đục ngà trắng của sữa dừa nảy giọt thanh kẹo ngấm cực rợn vị dẻo râm mát.\n- Cam kết y khoa an toàn: Không độn béo pha hóa chất tẩy sữa ôi ầm ẩm. Dừa thuỷ tinh tinh chất nạp Paster vặn chặt không biến dạng men uất độc chua nghét vi xẩm lọt thỏm.\n\n*Câu chuyện sản phẩm:*\nMột sự khiêu vũ táo bạo dầm rợn của hai vua giải khát nhiệt đới vẫy vùng dưới nắng nóng bờ nam. Nước dừa bẽo béo quánh vương lượn nấp cùng dãi yến thênh thanh chợp xoa dịu đi cơn khốc kiệt thiêu đốt bốc sương nám sạm đen của làn da phụ nữ dập thù lụa sương. Nó không chỉ là ly nước hám ngọt mà là thần dược giải áp nhan sắc mĩ từ rờ rỡ trong ánh mắt say đắm.",
    shortDescription: "Suối Lọc Giải Khát Đỉnh Cao Mùa Tóc Khô Nắng Nam - Khơi cấp nguồn nước làm mờ chân tàn nhang sắc bén bốc lột sạm tồi.",
    price: 170000,
    originalPrice: 200000,
    images: ["/images/products/readytoeat-coconut-1.png"],
    category: "READY_TO_EAT",
    benefits: ["Bồi lấp nước điện giải bù mồ hôi thoái trào mất canxi", "Phục hưng biểu bì bóc khô nẻ bong tróc tóc xơ vụn lả tả", "Vị ngon ngọt lạ lùng khó cưỡng thèm ừng ực nức thóp nhấp nhấp"],
    usage: "**HƯỚNG DẪN SỬ DỤNG CHUẨN KHOA HỌC:**\n- Nhiệt độ khẩu quyết nã dùng: Khuyến cáo bắt ép ủ siêu lạnh cứng. Nhét vào lồng đông dập tuyết 15 phút xong nốc sụp ực tức tốc ngay giữa buổi cái nắng châm chết điếng.\n- Khung thời gian rẽ nước độ: Khoái dồn tút nã vào xế trưa gắt nắng, hay hậu trận cày bộ chạy bộ Gym xéo tung mồi. \n- Mẹo vọc chất hỗn loạn: Có thế trộn đổ cùng đá xay, nhưng cấm kỵ để dừa bỏ lơi nắp vặn ngoài nhiệt độ 30 độ quá tiếng đồng hồ vì dễ men rêu lợ chua vi nhú.\n\n*Nghệ thuật thưởng thức:*\nĐổ cốc yến đê mê ra pha lê vò vo cuống lá Bạc Hà ngái miên xen lẫn cùng rắc đá viên lốm chốm lốc rốc như ly Cocktail Thanh Xuân Chống Nám khóc thét trả lại 18 tuồi bừng nhan gắp.",
    tags: ["beauty", "coconut", "collagen", "women"],
    stock: 180,
    averageRating: 4.7,
    reviewCount: 98,
    featured: false,
    active: true,
    weight: "70ml x 1 hũ",
    origin: "Bến Tre x Khánh Hòa",
  },
  {
    name: "Yến Chưng Collagen Hồng Sâm",
    slug: "yen-chung-collagen-hong-sam",
    description: "**THÔNG TIN SẢN PHẨM**\n- Phức hợp tinh linh công trình y sĩ học: Tích hợp 15% Yến gọng dệt đảo khơi pha cuộn mớ Collagen Peptide hạt lựu siêu dẫn (thu hẹp cỡ vi phân đánh lọt thẳng màng ruột siêu xoáy 300 Dalton).\n- Rẽ nước hợp bích Sâm Hồng tía: Khối đục hầm nhẫn mận màu tiêm tiết với rễ sâm đỏ phơi sấy công nghệ vạch kim đỉnh điểm phá đứt thói giằng xé bào mòn lão nát cấu trúc da mặt chảy xệ tuổi 3-4 dọc.\n- Độ cam kết thẩm mỹ: Làm phẳng rãnh kéo vạch nọng dũa cơ dướn nọng dưới mi, thúc buồng nội tiết buồng sinh nữ dãn nở sức thanh phôi xuân ngực.\n- Cam kết dán mác an toàn không pha trộn cồn men nhão hôi men bẩn mốc nồng váng khuẩn.\n\n*Câu chuyện sản phẩm:*\nUy Quyền Vực Dậy Mảng Cắt Lão Hóa! Hũ yến quyền lực này gầm thét vị nhẫn đắng ban đầu trên đầu lưỡi, nhưng ngay lập tức bùng nổ vỡ tung sự ngọt ngào cuống quýt từ dạ phế xốc ngược bốc lên thanh khí rát mũi nồng ấm đê mê. Nó là cỗ máy quay ngược kim đồng hồ, buộc làn da chầu chực nhăn rút phẳng mịn lại trong ánh mắt ghen tị của phàm trần.",
    shortDescription: "Ma thuật đỏ thắm Cỗ Máy Thổi Ngược Lão Già Đứt Chuỗi DNA Chẩy Xệ bằng chốt nọc Hồng Sâm đan giăng sợi Yến Collagen thần dược.",
    price: 250000,
    originalPrice: 300000,
    images: ["/images/products/readytoeat-collagen-1.png"],
    category: "READY_TO_EAT",
    benefits: ["Xóa xụp lấp đầy võng rãnh cười vết cung đường nhăn vạt vạc bọng mắt giật", "Truyền nổ sinh lực nữ cường hooc môn buồng trứng ục âm thầm đẻ sức khoe vạm đỏ da thắm", "Hồi phục bấu gân chóp dính kết giằng sụn cốt khớp đỡ xương lưng chống nhức bó co nát"],
    usage: "**HƯỚNG DẪN SỬ DỤNG CHUẨN KHOA HỌC:**\n- Mật độ tiếp nạp thuốc ma lực: Đây là cực phẩm công phu siêu mãnh bốc men sâm nữ thần đình. Cấm kỵ nốc liền hằng dọc mỗi ngày vung phí, chỉ thiết đặt liều dùng: 2 Cữ / Tuần cách ngày 3 hôm.\n- Khẩu tiết dạ bao tử trống rỗng rục rãnh: Phải tiêm ngậm rót lúc sáng sơ thức tỉnh khi mà bao tử trống bạo liệt, MẢY MAY KHÔNG UỐNG 1 giọt Sữa để Collagen bóp chặt xuyên qua màng vi tiển đi tọng chọc thẳng buồng da nếp gọng đê mê.\n- Chống chỉ định cấm kị ngầm: Phụ nữ mang thai yếu bẩm không nạp Sâm Hồng, người tăng đột kích hỏa huyết ác khốc.\n\n*Nghệ thuật thưởng thức:*\nCần thái độ tôn nghiêm trịnh trọng nếm. Cầm nắp giật gắp lên chợp cắn nhai vị sâm xác đắng lởn vởn kìm vị xong mới đẩy mạnh yến mượt mụ nhè qua yết hầu rụt vào hầm tâm can.",
    tags: ["beauty", "anti-aging", "collagen", "premium", "women"],
    stock: 100,
    averageRating: 4.8,
    reviewCount: 67,
    featured: true,
    active: true,
    weight: "70ml x 1 hũ",
    origin: "Sản phẩm công nghệ Liên Doanh",
  },
];

export const mockBlogPosts: Omit<BlogPostType, "id" | "createdAt">[] = [
  {
    title: "Cách Chưng Yến Sào Đúng Chuẩn Xưa Tại Nhà",
    slug: "cach-chung-yen-sao-dung-chuan",
    content: `# Bí Quyết Chưng Yến Cách Tường: Âm Hưởng Hoàng Cung Chậm Rãi\n\nGiữa cuộc sống vội vã hối hả, có một khoảnh khắc bạn đứng lại bên gian bếp nhỏ, nâng niu đóa hoa yến trắng ngà, thả nhẹ vào thố men rạn màu lam ngọc. Chưng yến - đó không chỉ là thao tác bật bếp. Nó là một nghệ thuật tu tập tính nhẫn nại, tĩnh tâm, được truyền đời từ những yến bào chốn Ngự Thiện Phòng triều Nguyễn.\n\n## Chương 1: Đánh Thức Nữ Thần Biển (Quá trình ngâm)\nĐừng bao giờ dội nước sôi vào yến! Nó tàn nhẫn như việc phá tan những chuỗi peptide tinh túy nhạy cảm sinh học. Hãy rót nước tinh khiết ủ lạnh hoặc nhiệt độ phòng mơn man ngâm yến.\nSự chờ đợi có thể lê thê từ 30 phút đến vài giờ tùy theo độ cộm của yến thô. Nhẹ nhàng ngắm phiến yến bở tơi mềm mại, bung tỏa thành những dải lụa mỏng tang dập dềnh trong thố nước pha lê.\n\n## Chương 2: Làm Sạch Lông Mang Cả Trái Tim\nNếu đó là yến còn lông, thì chiếc nhíp tinh vi và đôi mắt điềm đạm là vũ khí. Bạn đang gạt bỏ tạp niệm của bản thân khi gắp từng chiếc lông tơ đen nhẻm vướng víu vào tơ trắng xốp. Một cái rây nếp xả trực diện dưới dòng lệ trong veo từ vòi nước sẽ giúp làm trôi sạch lớp rêu mục bám đáy yến. Rửa vừa đủ dịu dàng để không đứt ruột yến ngọc.\n\n## Chương 3: Cuộc Giao Tranh Chậm Rãi Trên Bếp Lửa\nTuyệt chiêu chưng Yến nằm ở cụm từ: **Cách Thủy Rung Động Nhẹ**.\n- Cho đóa yến no nước vào thố sứ có nắp nhỏ lọt thỏm. Đổ nước vừa xăm xắp cách đỉnh yến 1 đốt tay.\n- Đặt thố sâu vào một chiếc nồi lớn đang thầm thì reo nước hâm hấp 85 độ C.\n- Đừng để nước ngoài nồi sùng sục trào bọt tung toé, chỉ giữ lửa nhỏ li ti. Đóng nắp kín bưng để phong tỏa nhiệt hơi.\n\nKhoảng thời gian 25 - 30 phút cạn kiệt, hương tỏa thơm lừng mùi thanh thanh ngai ngái mùi trứng. Ngay lúc đó, hãy xắn hạt đường phèn Quảng Ngãi xốp rỗng rắc vào cùng vài vệt gừng thái chỉ. Đóng nắp đun sập thêm 5 phút cuối.\n\nNhấc chén ngọc ra. Đặt khẽ nếm một thìa. Một dòng ấm dẻo quánh tan lấp vào thực quản, sự thanh tĩnh của đại dương tràn ngập bao tử rỗng tuếch. Cảm ơn thiên nhiên hoang dã.`,
    excerpt: "Nghệ thuật chưng yến cung đình - Gỡ bỏ mọi sai lầm nấu nướng làm đứt gãy mạch dưỡng chất quý giá của món quà tinh túy này.",
    coverImage: "/images/blog/blog-cooking.png",
    tags: ["hướng dẫn", "chưng yến", "mẹo hay", "ẩm thực"],
    published: true,
  },
  {
    title: "10 Lợi Ích Sức Khỏe Tuyệt Vời Của Yến Sào - Thần Dược Huyền Bí Giữa Lòng Khơi Xa",
    slug: "loi-ich-suc-khoe-yen-sao",
    content: `# Phá Bỏ Nút Thắt Sinh Tử Cuộc Đời Nhờ Tinh Chất Giọt Sương Rơi\n\nXưa kia, các vua chúa vì khao khát trường sinh bất lão đã cho quân lính trèo treo leo bên vách núi dựng đứng đánh cược cả sinh mạng chỉ để mang về những chiếc tổ làm từ bọt dãi chim yến nhỏ xíu rỉ máu. Tại sao lại trả cái giá đắt nhường ấy? Hôm nay khoa học đã khám phá 10 mã gen cực phẩm bị giấu kín trong đó:\n\n## 1. Nguồn Bơm Năng Lượng Miễn Dịch Bất Bại\nAxit Sialic chiếm cực kỳ cao - đó là "bức tường khiên khiên bọc" hoàn hảo cản lại cả rổ vi khuẩn, vi trùng tấn công xâm nhập đường hô hấp mà người xưa ngợi ca là Dưỡng Vệ Khí Hoàn Mỹ.\n\n## 2. EGF - Chìa Khóa Cải Lão Hoàn Đồng Cho Phụ Nữ\nEpidermal Growth Factor - nhân tố vàng giúp lớp biểu bì tái tạo tốc độ gấp 3 lần bình thường. Chuỗi tế bào sừng chai vỡ ra, lộ làn da mỏng manh tươi trẻ tuổi 18 căng bóng mượt sương khói bay bay.\n\n## 3. Quét Sạch Phổi Giấy - Chữa Ho Viêm Ho khan\nVị ngọt thanh bình sảng khoái tính hàn của loại dãi yến đánh trực diện vào đờm nhầy kẹt sâu trong thanh quản con người, dọn dẹp sạch sẽ phế nang tổn thương sau các cơn hậu phẫu hô hấp viêm nhiễm kéo dài não nề.\n\n## 4. Nuôi Dưỡng Thánh Thể (Cho Bà Bầu)\nPhụ nữ cạn kiệt canxi thai nghén được tưới tắm lượng cực khủng Amino axit hỗ trợ bào thai tăng sinh xương chậu thần tốc từ trong bụng không mảy may gánh nặng gan thận.\n\n## 5. Đánh Rơi Stress Lên Chín Ngàn Dặm Mây Xanh\nCác chuỗi Threonine kéo não khỏi mệt mỏi cùng cực của những canh khuya mất ngủ, thả thần trí nhẹ bồng bềnh êm xui tựa dải sương mù.\n\n## 6. Món Ăn Dạ Dày Yêu Thích \nTrẻ nhỏ ốm yếu còi cọt thường đào thải thức ăn thịt cá thô rắn. Yến vào dạ dày dễ tiêu bốc khói thành tinh chất siêu vi lập tức lách qua thành ruột ngấm vào máu không tốn năng lượng tiêu hóa dạ dày bóp bao nhiêu tẹo nào.\n\n## 7. Đẩy Cửa Hồi Sinh Trí Nhớ \nPheylalanine, vi lượng đồng và kẽm thúc đẩy sự truyền dẫn qua hệ nơ-ron điện thần kinh tăng vọt - Người bệnh Alzheimer hay giới mọt sách căng não thi sẽ phải khâm phục sát bệ phóng logic bộ não khi được uống hũ yến chưng đều đặn ròng.\n\n## 8. Cứu Vương Cơ Đắp Vào Thân Mòn\nNgười sau hoá trị hóa chất độc địa, sụp cơ tay cơ cẳng - yến đưa valine và Isoleucine bồi phục lại những bó cơ bắp cứng đơ mệt rũ hồi sinh lại.\n\n## 9. Huyết Áp Yêu Dấu Nhu Hòa Lại Tim Vàng\nHạ nhiệt sự nổi loạn của những dòng máu phừng phực bơm sai nhịp tim vỡ nát, để cholesterol xấu tự động bị cuốn trôi vô thanh.\n\n## 10. Chặn Đứng Kim Đồng Hồ Oxy Hóa Nếp Nhăn\nMàng chống oxy hóa vô hình rình rập diệt gốc tự do hoành hành ngang ngược.`,
    excerpt: "Bạn đang sở hữu điều diệu kỳ gì bên trong từng chén súp trong suốt ấy? Tại sao Yến Sào lại được săn lùng ngàn năm trường kỳ?",
    coverImage: "/images/blog/blog-health.png",
    tags: ["sức khỏe", "yến sào", "dinh dưỡng", "khoa học"],
    published: true,
  },
  {
    title: "Yến Sào Cho Bà Bầu: Chặng Đường Nuôi Con Từ Trái Tim Huyết Mãnh",
    slug: "yen-sao-cho-ba-bau",
    content: `# Hành Trình Tôn Thờ Thiên Chức Nuôi Dưỡng Mần Hạt Của Mẹ Biển Cả\n\nLàm mẹ - là lúc cơ thể mong manh rút kiệt từng mẩu thanh xuân để kiến tạo nên hình dáng giọt máu lấp lánh sinh động. Nhiều bà mẹ bị bào mòn với chứng buồn nôn lả người ở kỳ thai nghén héo hắt nhợt nhạt. Tổ Yến lúc này không phải là "đồ đắt tiền chưng mua trọc phú" - mà là chiếc rễ ma mộc neo giữ sự kiên trì sinh mệnh thần thánh.\n\n## "Em Bé Thông Minh Phá Dớp - Từ Nguồn Axit Sialic"\nCác nghiên cứu khoa học Thụy Sỹ đã đổ gục thừa nhận rằng: Lượng Sialic dào dạt tích tụ trong yến đảo là viên gạch tiên phong xếp chồng thành mô cấu trúc Nơ-Ron Thần Kinh Thai Nhi Tối Đa Nhất. Ăn yến từ kỳ diệu thứ tháng 4, đứa bé cựa quậy đạp bung bụng mẹ bằng một trí não sáng rực khổng lồ tiềm ẩn. Phả hơi thở tinh khiết vào sự sống mới.\n\n## Ánh Chớp Trong Tam Cá Nguyệt Cấm Kỵ 3 Tháng Đầu\n"TIN ĐỒN HUYỀN BÍ: 3 tháng đầu mỏng manh nên không được đụng Yến tẩm bổ lạnh dạ?" \nSự thật ngã ngửa: Trong tam cá nguyệt đầu, mọi sự dập dồn xô bồ, nghén bủng rủng nôn mửa là cơn ám ảnh kinh hãi bòn rút dạ dày. Yến tính hàn lạnh - Sự khôn khéo tinh tế là hãy đun yến nhừ nát đặc kẹo lỏng với 2 lát gừng già mỏng. Một ly yến súp nóng hổi sẽ áp chế sóng dạ dày cuộn trào mà vẫn bơm được protein đỉnh của tinh túy, nạp lực mà không sợ thai lưu!\n\n## Lộ Trình Hoàn Mỹ Tuyệt Kỹ Bồi Thai:\n- Tháng thứ 4 -> Cuối tháng 7: Cứ 3 đêm ròng lại bật bếp đun 3-4 gam yến vàng ruộm chưng táo tàu ngọt lịm. Bé béo tròn bụ bẫm tăng ký cái vèo.\n- Tháng 8 -> Cận sát ngày đẻ rên la: Bà mẹ húp tổ yến đều đặn để chuẩn bị nội công vươn mình rặn đau giếng biển và hồi phục chống sa dạ con rách nát sau sanh đẻ cấp kì nhờ EGF liền mô!\n\nSợi chỉ dai giòn đó không đơn giản là thức ăn - Nó là dải băng bó dịu êm thắt chặt sợi dây liên kết máu mủ vô thời hạn.`,
    excerpt: "Sự thật đằng sau những quan niệm cấm kỵ 3 tháng đầu thai nhi. Phép màu thần đồng thông minh não bộ cho bé ngay từ lúc nằm phôi thai nôi ấm mẹ biển cả.",
    coverImage: "/images/blog/blog-pregnancy.png",
    tags: ["bà bầu", "thai kỳ", "dinh dưỡng mẹ và bé"],
    published: true,
  },
  {
    title: "Hướng Dẫn Tránh Sập Bẫy Mua Yến Gỉa Bằng Đôi Mắt Kim Giác Của Bậc Thầy Sành Ăn",
    slug: "huong-dan-chon-yen-sao-chat-luong",
    content: `# Chuyến Phiêu Lưu Trừ Tà Định Nhan Khám Phá Nghệ Thuật Chọn Yến Đỉnh Cao\n\nCầm hộp Yến giá chục triệu, cảm giác run rẩy sợ hãi nơm nớp trong ngực: "Liệu có dính bẫy nấm rong biển hồ tinh ngâm hóa chất cộp mác vua yến dối gian chăng?". Trong thương trường hỗn loạn phồn hoa này, hàng triệu tổ yến chắp vá bằng keo da bì da mủ nhan nhản khơi mào đại cục rác hôi thối. \nHãy là vị thám tử quyền uy bóc trần đường dây mánh mung này!\n\n## Mánh Mung Đội Lột Mặt Nạ "Keo Pha Túi Gói Trắng Phau"\nYến giả công nghiệp siêu ngụy trang: Người ta mua vụn vi bột yến pha dán sệt với agar rau câu, tinh bột khoai mì, thoa vuốt ve thành hình vóc cánh nôi tuyệt đẹp cứng đờ. Phơi nắng lên một mẻ "cực bóng loáng rợn người", trắng bóc vô tri mù quáng không tì vết. Ngâm vào nước 20 phút - lập tức bấy hầy vỡ tan tành hồ nhão nứt không hình hài mạch lạc.\n\n## Khai Nhãn Lực - Ánh Sáng Chắp Vá \nLấy ngay chiếc đèn pin di động soi từ ánh ngược: Nếu từng sợi xớ chằng chéo rối ren đong vào có tia tia không đều đặn vồng uốn lồng, màu hơi ố kem trứng nham nhở - Xin chúc mừng, Mẹ tự nhiên đang mỉm cười với bạn chân ái.\nCắn ngẫu nhiên 1 góc tổ khô cứng: Vị giòn vụn kêu vỡ rốp như mảnh kính xé - là yến chuẩn. Còn hơi bị bẻ dai nhách dẻo dẻo kẹo kéo uốn cạy khó khăn - Rõ ràng bị xịt đường giữ ẩm ăn gian trọng lượng chục gam nặng cân thu tiền ác liệt!\n\n## Thử Quỳ Tím - Vua Lửa Dặm Mặt Yến Yêu Ma \nTàn sát lửa khò tàn khốc: Cầm 1 ngẫu nhiên nhón nhỏ quăng bật lửa đốt. Mùi bánh gai, hồ bột khen khét lẹm mũi tro xỉ đen - yến rác giả nhựa.\nMùi đặc quánh khét cháy hữu cơ sừng lông của sừng tê nai - đấy chính là sảnh điện đanh tự nhiên của tinh hoa thật chuẩn quốc hồn quốc túy vạn vạn năm ròng.\n\nNgười tiêu dùng sành điệu là thanh kiếm thép phán quyết cuối cùng loại bỏ mọi chiêu trò trên thánh đường sức khoẻ.`,
    excerpt: "Lột trần mánh lới độn keo, ép mủ, phủ bột trắng phau tại các xưởng gia công đen tối. Trang bị khả năng soi tia thấu thị đâm thủng đồ giả lừa phỉnh ngay trong ánh mắt liếc nhìn 3 giây đầu.",
    coverImage: "/images/blog/blog-quality.png",
    tags: ["hướng dẫn", "chọn yến", "chất lượng", "cảnh báo"],
    published: true,
  },
  {
    title: "Sự Tích Huyết Yến Cùng Lời Đồn Về Giọt Máu Bi Thương Đam Mê Của Loài Chim Ngốc Lễ",
    slug: "su-tich-huyet-yen-va-loi-don",
    content: `# Tiếng Kêu Rỉ Máu Ban Đêm, Vọng Khắp Hang Sâu Lý Sơn Nước Lặng\n\nNhân gian xưa kể một trong những giai thoại xót xa và đẹp bậc nhất giới tự nhiên. Rằng loài chim Yến hằng đêm mải miết xây mạn tổ cho vợ con tị nạn gió vách cheo leo trên các hòn đảo tít tắp ngất trời. Tiết trời ác khắc bào mòn, nước bọt kiệt quệ ráo trơn. Chim bố gồng cổ họng lên nức nở khạc ho ra máu pha dãi đơm để cố gắn vá víu phần tổ nham nhở cho xong rạng rạng sáng ban mai. Những giọt huyết bầm quánh lại hằng tháng, khô nhuộm cả vạt bọt trắng ngà thành một màu đỏ thâm mận bí ẩn... \nĐó là sự mở đầu ly kỳ bi diệu về Huyền thoại Huyết Yến.\n\n## Đập Tan Mytos (Sự Thật Kế Tiếp) Khoa Học Trần Trụi Giáng Đòn \nSự thật có mĩ miều đau lòng đến chừng mực ấy không? \nThật mỉa mai lẫn thú vị: Chim Yến KHÔNG HỀ khạc rỉ máu để xịt xây tổ nào cả. Giọt máu rỉ nứt cuống họng khi kết tổ cứng dính là truyền thuyết mị dân huyễn hoặc do dân buôn thêu dệt đẩy giá Huyết Yến lên trăm triệu đồng/lạng chục phân!\n\nSân khấu thật sự xảy ra ở các hang động tối ẩm rêu xanh ngấm đá xỉ tro đen. Phân hóa học chuỗi phản ứng cực độc quyền ở dưới đáy hang mịt mù bốc lên hàm lượng Nitrit/Amoniac siêu cực mạnh bốc hơi ngấm quệ vào tảng thạch cao nơi chim bấu ngự. Vài chục ngàn năm, vạt yến trắng ngấm men hơi khí này ủ mầm lên men rực lửa chuyển sắc đổi cam thẫm rồi đỏ mận uy nghiêm.\n\n## Quyền Năng Của Sự Tái Sinh Quả Tim \nNhưng tại sao Huyết Yến (Yến Cầm Huyết) không bị phá giá đào thải?\nTuy không là giọt máu nghĩa khí bi thương, nhưng sự ủ men vách động tự nhiên tùng vạn năm đã ban cho Huyết Yến một hàm lượng sắt Oxit Iron Fe2+ siêu siêu đậm đặc ngấm lên gấp 50 lần sợi yến đảo thông thường. Yến hấp thụ linh khí thổ địa và trở thành một phương thuốc thần cường cực cường não - bổ dương và trị những chứng bệnh u thâm ung nhọt do cạn máu di truyền khốc liệt tận cốt tủy.\n\nBạn có dám uống chén yến rực đỏ này dầm chìm trong chén cổ men rạn đời nhà Minh để kết nối cùng nhịp thời gian xưa?`,
    excerpt: "Chim Yến ho lao tự khạc máu xây tổ để lại những dòng nước bọt ám ảnh đỏ quánh lộng lẫy? Đập tan màn sương mù mờ ảo và chạm đến lời giải khoa học chân ái giật mình phía sau hòn đá rêu phong Huyết Yến Tôn Quý Bậc Nhất Đế Vương.",
    coverImage: "/images/blog/blog-rednest.png",
    tags: ["khoáng thạch", "huyết yến", "truyền thuyết", "khám phá"],
    published: true,
  },
  {
    title: "Hành Trình Sinh Tử Mạo Hiểm Bước Chân Gọi Yến Về Đảo Quần Thể Lạnh Lẽo Ly Sơn",
    slug: "hanh-trinh-sinh-tu-goi-yen-dao-ly-son",
    content: `# Rơi Tự Do Xuống Rặng Đá San Hô Găm Mũi Căm - Cái Giá Của Vua Đảo\n\nGió rít bạt mạng quật từng cơn rung đứt đoạn những mảng lưới dây rợ vươn lơ lững bám vách núi dựng đứng nhọn hoắt gặm đầy lưỡi cưa rong mặn chát của đảo hoang. Đứng tận dưới này, con người chỉ là con kiến đen bám chênh vênh ở độ cao hàng chục mét xé mây mờ.\n\n## Cọng Thép Đung Đưa Và Sào Trúc Phơi Linh Hồn \nNghề thu hái vách yến đảo không dành cho người gầy thân thần kinh yếu đuối. Mỗi năm hai mùa khắc nghiệt sóng dữ bão chồm, dàn xà tre mong manh chằng chống mấp mô đóng vào khe kẽ chông chênh nham thạch đá núi. Dây thừng thắt chặt hông căng đứt lựt mạch máu cơ bụng bấu ghịt. \nNgười thợ đu người treo lơ lửng, tay cầm kẹp cong, nhãn mạn xịt xịt soi đèn pin vào sâu hút con mắt động hang tối sầm ngực lạnh lẽo tiếng dơi rít để móc từng tảng bạch ngà cẩn thận nguyên vẹn cho vào lưới vải bố đeo hông. Sảy chân - 1 giây định nghĩa vĩnh biệt!\n\n## Quyết Tâm Xây Lãnh Địa Nhử Loài Chim Lang Thang Kiêu Ngạo Trở Về Lập Tổ Dựng Xây Cộng Đồng \nLàng đảo Lý Sơn đang dần mất chim về vùng khai thác hỗn loạn khép đục. Đám thanh niên quyết chí mở sừng bám biển. Một hành trình khàn rã cổ tái thiết hang vách giả lập mọc đầy thiết bị loa sóng tần số vang nhại lại tiếng cạ xù xịt chít chít văng vọng trong đêm khuya rùng rợn thanh thanh hút hút. Ròng rã suốt 5 năm, mùi phân vương bạt chim ủ kỹ, mùi bầy đàn êm ấm sưởi lửa được giả mạn đánh bật.\n\nRồi phép màu xuất hiện! Hằng hà sa số đám bụi đen mịt trời từ đằng biển khơi xa xăm hàng hải đùn xô bay vút vào miệng hang rộng ồm oàm há hố. Quần thể phục hưng! Những sợi yến dày uỳnh phết lên mép xiềng đá lạnh lại chói dội mọc san sát.\nKhi thưởng thức chén chè yến đảo thơm lừng đặc dẻo, nào mấy ai biết đằng sau một mùi tanh man mác kiêu ngạo ấy là nước gân bắp thịt vã ra đổ mồ hôi liều cược tính phận con vượn khổng lồ trần gian hoang dại trần trụi ngoài khơi bão khốc mịt mờ!`,
    excerpt: "Cận cảnh trải nghiệm đẫm mồ hôi, sinh tử lơ lửng vách đá lưỡi cưa sâu không lối thoát để đánh cược lấy vài gam tinh chất tổ chim trong đêm tối mù khơi gió thét.",
    coverImage: "/images/blog/blog-origin.png",
    tags: ["nghề biển", "yến đảo thiên nhiên", "câu chuyện", "hành trình"],
    published: true,
  }
];

export const mockDiscountCodes = [
  {
    code: "YENSAO10",
    type: "PERCENTAGE" as const,
    value: 10,
    minOrderValue: 500000,
    maxUses: 100,
    usedCount: 23,
    validFrom: new Date("2024-01-01"),
    validTo: new Date("2027-12-31"),
    active: true,
  },
  {
    code: "FREESHIP",
    type: "FIXED" as const,
    value: 30000,
    minOrderValue: 300000,
    maxUses: 200,
    usedCount: 67,
    validFrom: new Date("2024-01-01"),
    validTo: new Date("2027-12-31"),
    active: true,
  },
  {
    code: "WELCOME20",
    type: "PERCENTAGE" as const,
    value: 20,
    minOrderValue: 1000000,
    maxUses: 50,
    usedCount: 12,
    validFrom: new Date("2024-01-01"),
    validTo: new Date("2027-12-31"),
    active: true,
  },
];

export const mockReviews = [
  { rating: 5, comment: "Yến rất ngon, sợi dày dai. Gia đình mình rất hài lòng!", userName: "Nguyễn Thanh Hoa" },
  { rating: 5, comment: "Mua làm quà biếu Tết, bao bì sang trọng, người nhận rất thích.", userName: "Trần Văn Minh" },
  { rating: 4, comment: "Chất lượng tốt, giao hàng nhanh. Sẽ mua lại lần sau.", userName: "Lê Thị Mai" },
  { rating: 5, comment: "Dùng cho bà bầu 3 tháng rất tốt, da đẹp lên nhiều.", userName: "Phạm Thị Hồng" },
  { rating: 4, comment: "Yến chưng sẵn tiện lợi, vị ngon tự nhiên.", userName: "Hoàng Đức Anh" },
  { rating: 5, comment: "Mua cho mẹ dùng hàng tháng, sức khỏe cải thiện rõ rệt.", userName: "Võ Minh Tuấn" },
];
